-- Database: CRS
 USE CRS;

-- Add column to capture the province
ALTER TABLE COURTS ADD COLUMN provinceUKey int(11) NOT NULL;

-- Update Court details (Add province)
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 1;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 2;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 3;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 4;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 5;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 6;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 7;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 8;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 9;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 10;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 11;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 12;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 13;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 14;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 15;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 16;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 17;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 18;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 19;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 20;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 21;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 22;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 23;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 24;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 25;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 26;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 27;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 28;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 29;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 30;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 31;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 32;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 33;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 34;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 35;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 36;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 37;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 38;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 39;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 40;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 41;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 42;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 43;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 44;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 45;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 46;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 47;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 48;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 49;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 50;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 51;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 52;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 53;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 54;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 55;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 56;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 57;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 58;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 59;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 60;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 61;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 62;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 63;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 64;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 65;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 66;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 67;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 68;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 69;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 70;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 71;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 72;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 73;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 74;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 75;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 76;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 77;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 78;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 79;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 80;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 81;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 82;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 83;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 84;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 85;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 86;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 87;
UPDATE COURTS SET provinceUKey = 1 WHERE courtUKey = 88;

-- Add Foreign key constraint
ALTER TABLE COURTS ADD CONSTRAINT `FK_Courts_Province_provinceUKey` FOREIGN KEY (`provinceUKey`) REFERENCES `COMMON`.`PROVINCE` (`provinceUKey`);

