-- Database: PRS
USE PRS;

-- Update Name in English
UPDATE PERSON SET fullNameInEnglishLanguage = 'WEERAPPULIGE ARUNA CHINTHAKA' WHERE personUKey = 505;
UPDATE PERSON SET fullNameInEnglishLanguage = 'WANASURIYA MUDIYANSELAGE SAMANTHA UDAYAKUMARA ARIYARATHNA' WHERE personUKey = 509;
UPDATE PERSON SET fullNameInEnglishLanguage = 'KOTABOGODA HANGIDIGEDARA UDITHA GIHAN' WHERE personUKey = 512;
UPDATE PERSON SET fullNameInEnglishLanguage = 'KURUMBA PITIYALAGE MANJULA PRASAD RANAWEERA' WHERE personUKey = 515;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MOHAMED HAZMIL HAMDOON' WHERE personUKey = 518;
UPDATE PERSON SET fullNameInEnglishLanguage = 'PALLAWALAGE UDESH MANJULA' WHERE personUKey = 522;
UPDATE PERSON SET fullNameInEnglishLanguage = 'DARSHANA JAYARANGA ALUTHWEEDIYE KORALA' WHERE personUKey = 526;
UPDATE PERSON SET fullNameInEnglishLanguage = 'ABDEEN MOHAMED AZAR' WHERE personUKey = 530;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MOHAMED LAFIR MUHAMMAD FAZAL' WHERE personUKey = 533;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MOHAMED FARHAN JURANGPATHY' WHERE personUKey = 536;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MOHAMED NAIZER MAKEEN' WHERE personUKey = 539;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MOHAMED HASSAN MOHAMED FAZMI' WHERE personUKey = 542;
UPDATE PERSON SET fullNameInEnglishLanguage = 'WATARAKA GAMAGE DHANUSHA DUMINDA' WHERE personUKey = 546;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MUHAMMED FAZY MUHAMMED MISHAK' WHERE personUKey = 549;
UPDATE PERSON SET fullNameInEnglishLanguage = 'ABDUL RAUFF SALMANUL FAREES' WHERE personUKey = 552;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MOHAMED RAFEEK MOHAMED RIZAN' WHERE personUKey = 555;
UPDATE PERSON SET fullNameInEnglishLanguage = 'RAMANAYAKAGE WIMALARATNA' WHERE personUKey = 558;
UPDATE PERSON SET fullNameInEnglishLanguage = 'KORALAGAMAGE ANIRA NISHANTHA JAYAWARDHANA' WHERE personUKey = 561;
UPDATE PERSON SET fullNameInEnglishLanguage = 'SELLADURAI SENADHIRAJA' WHERE personUKey = 565;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MANIKKU BADATHURUGE GIHAN RANGANA' WHERE personUKey = 569;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MOHAMED ASLAM NIJAM' WHERE personUKey = 573;
UPDATE PERSON SET fullNameInEnglishLanguage = 'MUMINKHAN MOHAMED ASHAD' WHERE personUKey = 1213;
