INSERT INTO COMMON.APP_PARAMETERS(NAME, VALUE) VALUES('crs.birth.late_reg_days', '90');
  
INSERT INTO COMMON.COUNTRIES (COUNTRYID, SICOUNTRYNAME, ENCOUNTRYNAME, TACOUNTRYNAME) VALUES(1, 'ශ්‍රී ලංකාව', 'Sri Lanka', 'ஸ்ரீ லங்கா');
INSERT INTO COMMON.COUNTRIES (COUNTRYID, SICOUNTRYNAME, ENCOUNTRYNAME, TACOUNTRYNAME) VALUES(2, 'ජපානය', 'Japan', 'ஜப்பான்');
INSERT INTO COMMON.COUNTRIES (COUNTRYID, SICOUNTRYNAME, ENCOUNTRYNAME, TACOUNTRYNAME) VALUES(3, 'ඉන්දියාව', 'India', 'இந்திய');

INSERT INTO COMMON.RACES (RACEID, SIRACENAME, ENRACENAME, TARACENAME) VALUES(1, 'සිංහල', 'Sinhalese', 'சின்ஹலேசே');
INSERT INTO COMMON.RACES (RACEID, SIRACENAME, ENRACENAME, TARACENAME) VALUES(2, 'ශ්‍රී ලංකික දෙමල', 'Sri Lankan Tamil', 'ஸ்ரீ லங்கன் தமிழ்');
INSERT INTO COMMON.RACES (RACEID, SIRACENAME, ENRACENAME, TARACENAME) VALUES(3, 'ඉන්දියානු දෙමල', 'Indian Tamil', 'இந்தியன் தமிழ்');

INSERT INTO CRS.BD_DIVISIONS (DISTRICTID, DIVISIONID, SIDIVISIONNAME, ENDIVISIONNAME, TADIVISIONNAME) VALUES(11, 1, 'කොළඹ කොටුව (Medical)', 'Colombo Fort (Medical)', 'கொலோம்போ போர்ட் (MEDICAL)');
INSERT INTO CRS.BD_DIVISIONS (DISTRICTID, DIVISIONID, SIDIVISIONNAME, ENDIVISIONNAME, TADIVISIONNAME) VALUES(11, 2, 'කොම්පන්න වීදීය (Medical)', 'Colombo Fort (Medical)', 'ச்லவே இச்லாந்து (MEDICAL)');
INSERT INTO CRS.BD_DIVISIONS (DISTRICTID, DIVISIONID, SIDIVISIONNAME, ENDIVISIONNAME, TADIVISIONNAME) VALUES(11, 3, 'අලුත් කඩේ (Medical)', 'Colombo Fort (Medical)', 'அழுத் கடி (MEDICAL)');

INSERT INTO COMMON.ROLES (ROLEID, NAME) VALUES('RG', 'Registrar General');
INSERT INTO COMMON.ROLES (ROLEID, NAME) VALUES('ARG', 'Additional Registrar General');
INSERT INTO COMMON.ROLES (ROLEID, NAME) VALUES('DR', 'District Registrar');
INSERT INTO COMMON.ROLES (ROLEID, NAME) VALUES('ADR', 'Additional District Registrar');
INSERT INTO COMMON.ROLES (ROLEID, NAME) VALUES('DEO', 'Data Entry Operator / Clerk');

INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT, ASSIGNEDDISTRICT, ASSIGNEDBDDIVISION) VALUES('user', '100', 'Sample DEO / Clerk', 'W6ph5Mm5Pz8GgiULbPgzG37mj9g=', 'SI', 11, 11, 1);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT, ASSIGNEDDISTRICT, ASSIGNEDBDDIVISION) VALUES('adr', '101', 'Sample ADR user', 'W6ph5Mm5Pz8GgiULbPgzG37mj9g=', 'SI', 11, 11, 1);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('dr', '102', 'Sample DR user', 'W6ph5Mm5Pz8GgiULbPgzG37mj9g=', 'SI', 11);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('arg', '103', 'Sample ARG user', 'W6ph5Mm5Pz8GgiULbPgzG37mj9g=', 'SI', 11);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('rg', '104', 'Sample RG user', 'W6ph5Mm5Pz8GgiULbPgzG37mj9g=', 'SI', 11);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('admin', '105', 'Sample System Admin', 'W6ph5Mm5Pz8GgiULbPgzG37mj9g=', 'SI', 11);

INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('ashoka', '201', 'Ashoka Ekanayake', 'XJRyDE28JvEY2IGylnz+w5CnnTA=', 'SI', 11);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('asankha', '202', 'Asankha Perera', 'JZiuu/n4ImMnYfxJ+ttGR9LyYmo=', 'SI', 11);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('duminda', '203', 'Duminda', '8OYuek4Vs7ebel1Trtm4sy8tB8w=', 'SI', 11);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('indunil', '204', 'Indunil', 'JZEs/79kaLxs0n4DOER6fN1vKLY=', 'SI', 11);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('amith', '205', 'Amith', 'RI/xsIJu3GrYsfWr2sLPf88I+Ks=', 'SI', 11);
INSERT INTO COMMON.USERS (USERID, PIN, USERNAME, PASSWORDHASH, PREFLANGUAGE, PREFDISTRICT) VALUES('chathuranga', '206', 'Chathuranga', 'hEFeb6UFV1Kxst3H0N9p/Ics/dI=', 'SI', 11);

INSERT INTO COMMON.USER_ROLES VALUES('user', 'DEO');
INSERT INTO COMMON.USER_ROLES VALUES('adr', 'ADR');
INSERT INTO COMMON.USER_ROLES VALUES('dr', 'DR');
INSERT INTO COMMON.USER_ROLES VALUES('arg', 'ARG');
INSERT INTO COMMON.USER_ROLES VALUES('rg', 'RG');
INSERT INTO COMMON.USER_ROLES VALUES('rg', 'ADR');

INSERT INTO COMMON.USER_ROLES VALUES('ashoka', 'ADR');
INSERT INTO COMMON.USER_ROLES VALUES('asankha', 'ADR');
INSERT INTO COMMON.USER_ROLES VALUES('duminda', 'ADR');
INSERT INTO COMMON.USER_ROLES VALUES('indunil', 'ADR');
INSERT INTO COMMON.USER_ROLES VALUES('amith', 'ADR');
INSERT INTO COMMON.USER_ROLES VALUES('chathuranga', 'ADR');


