CREATE TABLE APP_PARAMETERS (
    NAME      VARCHAR(25) NOT NULL,
    VALUE     VARCHAR(40),
    PRIMARY KEY(NAME)
);

INSERT INTO APP_PARAMETERS(NAME, VALUE) VALUES('crs.birth.late_reg_days', '90');

CREATE TABLE DISTRICTS ( 
    DISTRICTID       INTEGER NOT NULL,
    SIDISTRICTNAME   VARCHAR(25),
    ENDISTRICTNAME   VARCHAR(25),
    TADISTRICTNAME   VARCHAR(25),
    ACTIVE           SMALLINT WITH DEFAULT 1,
    PRIMARY KEY(DISTRICTID)
);

INSERT INTO DISTRICTS (DISTRICTID, SIDISTRICTNAME, ENDISTRICTNAME, TADISTRICTNAME) VALUES(11, 'කොළඹ', 'Colombo', 'கொழும்பு');
INSERT INTO DISTRICTS (DISTRICTID, SIDISTRICTNAME, ENDISTRICTNAME, TADISTRICTNAME) VALUES(31, 'ගාල්ල', 'Galle', 'காலி');
INSERT INTO DISTRICTS (DISTRICTID, SIDISTRICTNAME, ENDISTRICTNAME, TADISTRICTNAME) VALUES(22, 'මහනුවර', 'Kandy', 'கண்டி');

CREATE TABLE COUNTRIES (
    COUNTRYID        INTEGER NOT NULL,
    SICOUNTRYNAME    VARCHAR(25),
    ENCOUNTRYNAME    VARCHAR(25),
    TACOUNTRYNAME    VARCHAR(25),
    ACTIVE           SMALLINT WITH DEFAULT 1,
    PRIMARY KEY(COUNTRYID)
);

INSERT INTO COUNTRIES (COUNTRYID, SICOUNTRYNAME, ENCOUNTRYNAME, TACOUNTRYNAME) VALUES(1, 'ශ්‍රී ලංකාව', 'Sri Lanka', 'ஸ்ரீ லங்கா');
INSERT INTO COUNTRIES (COUNTRYID, SICOUNTRYNAME, ENCOUNTRYNAME, TACOUNTRYNAME) VALUES(2, 'ජපානය', 'Japan', 'ஜப்பான்');
INSERT INTO COUNTRIES (COUNTRYID, SICOUNTRYNAME, ENCOUNTRYNAME, TACOUNTRYNAME) VALUES(3, 'ඉන්දියාව', 'India', 'இந்திய');

CREATE TABLE RACES (
    RACEID           INTEGER NOT NULL,
    SIRACENAME       VARCHAR(25),
    ENRACENAME       VARCHAR(25),
    TARACENAME       VARCHAR(25),
    ACTIVE           SMALLINT WITH DEFAULT 1,
    PRIMARY KEY(RACEID)
);

INSERT INTO RACES (RACEID, SIRACENAME, ENRACENAME, TARACENAME) VALUES(1, 'සිංහල', 'Sinhalese', 'சின்ஹலேசே');
INSERT INTO RACES (RACEID, SIRACENAME, ENRACENAME, TARACENAME) VALUES(2, 'ශ්‍රී ලංකික දෙමල', 'Sri Lankan Tamil', 'ஸ்ரீ லங்கன் தமிழ்');
INSERT INTO RACES (RACEID, SIRACENAME, ENRACENAME, TARACENAME) VALUES(3, 'ඉන්දියානු දෙමල', 'Indian Tamil', 'இந்தியன் தமிழ்');

CREATE TABLE BD_DIVISIONS (
    DISTRICTID       INTEGER NOT NULL,
    DIVISIONID       INTEGER NOT NULL,
    SIDIVISIONNAME   VARCHAR(25),
    ENDIVISIONNAME   VARCHAR(25),
    TADIVISIONNAME   VARCHAR(25),
    ACTIVE           SMALLINT WITH DEFAULT 1,
    PRIMARY KEY(DISTRICTID, DIVISIONID),
    FOREIGN KEY (DISTRICTID) REFERENCES DISTRICTS(DISTRICTID)  
);

INSERT INTO BD_DIVISIONS (DISTRICTID, DIVISIONID, SIDIVISIONNAME, ENDIVISIONNAME, TADIVISIONNAME) VALUES(11, 1, 'කොළඹ කොටුව (Medical)', 'Colombo Fort (Medical)', 'கொலோம்போ போர்ட் (MEDICAL)');
INSERT INTO BD_DIVISIONS (DISTRICTID, DIVISIONID, SIDIVISIONNAME, ENDIVISIONNAME, TADIVISIONNAME) VALUES(11, 2, 'කොම්පන්න වීදීය (Medical)', 'Colombo Fort (Medical)', 'ச்லவே இச்லாந்து (MEDICAL)');
INSERT INTO BD_DIVISIONS (DISTRICTID, DIVISIONID, SIDIVISIONNAME, ENDIVISIONNAME, TADIVISIONNAME) VALUES(11, 3, 'අලුත් කඩේ (Medical)', 'Colombo Fort (Medical)', 'அழுத் கடி (MEDICAL)');

