CREATE TABLE app_parameters (
    NAME      VARCHAR(25),
    VALUE     VARCHAR(40)
);

INSERT INTO app_parameters(NAME, VALUE) VALUES('crs.birth.late_reg_days', '90');

CREATE TABLE districts ( 
    ID               INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DISTRICTID       INTEGER,
    DISTRICTNAME     VARCHAR(25),
    LANGUAGEID       VARCHAR(5)
);

INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(1, 'කොළඹ', 'si_LK');
INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(2, 'ගාල්ල', 'si_LK');
INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(3, 'මහනුවර', 'si_LK');

INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(1, 'Colombo', 'en_US');
INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(2, 'Galle', 'en_US');
INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(3, 'Kandy', 'en_US');

INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(1, 'கொழும்பு', 'ta_LK');
INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(2, 'காலி', 'ta_LK');
INSERT INTO districts (DISTRICTID, DISTRICTNAME, LANGUAGEID) VALUES(3, 'கண்டி', 'ta_LK');


CREATE TABLE countries (
    ID               INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    COUNTRYID        INTEGER,
    COUNTRYNAME      VARCHAR(25),
    LANGUAGEID       VARCHAR(5)
);

INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(1, 'ශ්‍රී ලංකාව', 'si_LK');
INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(2, 'ජපානය', 'si_LK');
INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(3, 'ඉන්දියාව', 'si_LK');

INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(1, 'Sri Lanka', 'en_US');
INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(2, 'Japan', 'en_US');
INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(3, 'India', 'en_US');

INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(1, 'ஸ்ரீ லங்கா', 'ta_LK');
INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(2, 'ஜப்பான்', 'ta_LK');
INSERT INTO countries (COUNTRYID, COUNTRYNAME, LANGUAGEID) VALUES(3, 'இந்திய', 'ta_LK');
