CREATE DATABASE `COMMON`
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE `CRS`
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE `PRS`
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;