INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName,  active)  VALUES(3, 5, 'Sammanthranapura', 'සම්මන්ත්‍රණපුර', 'ஸம்மந்திரணபுரை',1);
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(3, 10, 'Mattakkuliya', 'මට්ටක්කුලිය', 'மட்டக்குளி', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(3, 15, 'Modara', 'මෝදර', 'மோத‍ரை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(3, 20, 'Madampitiya', 'මඩම්පිටිය', 'மாதம்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(3,5, 'Mahawatta', 'මහවත්ත', 'மஹவத்தை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 30, 'Aluthmawatha', 'අළුත්මාවත', 'அளுத்மாவத்தை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 35, 'Lunupokuna', 'ලුණුපොකුණ', 'ளுணு‎பொக்குண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 40, 'Bloemendhal', 'බ්ලුමැන්ඩල්', 'புளூ‎மெண்டல்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 45, 'Kotahena East', 'කොටහේන නැගෙනහිර', '‎கொட்டாஞ்‍சேணை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 50, 'Kotahena West', 'කොටහේන  බටහිර', '‎கொட்டாஞ்‍சேணை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 55, 'Kochchikade North', 'කොච්චිකඩේ උතුර', '‎கொச்சிகடை வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 60, 'Jinthupitiya', 'ජින්තුපිටිය', 'ஜிந்துப்பிட்டி', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 65, 'Massangasweediya', 'මසන්ගස් විදිය', 'மஸங்கஸ் வீதி', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 70, 'New Bazaar', 'නිව් බසාර්', 'புது பசார்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 75, 'Grandpass South', 'ග්‍රෑන්ඩ්පාස් දකුණ', 'கி‍ரேண்ட்பாஸ் ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 80, 'Grandpass North', 'ග්‍රෑන්ඩ්පාස්  උතුර', 'கி‍ரேண்ட்பாஸ் வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 85, 'Nawagampura', 'නවගම්පුර', 'நவகம்புர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 90, 'Maligawatta East', 'මාලිගාවත්ත  නැගෙනහිර', 'மாலிகாவத்தை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 95, 'Bettarama', 'බෙත්තාරාම', '‎கெத்தாராமை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 100, 'Aluthkade East', 'අළුත්කඩේ  නැගෙනහිර', 'புதுக்கடை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 105, 'Aluthkade West', 'අළුත්කඩේ බටහිර', 'புதுக்கடை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 110, 'Kochchikade South', 'කොච්චිකඩේ  දකුණ', '‎கொச்சிக்கடை தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 115, 'Pettah', 'පිටකොටුව', 'புறக்‍கோட்டை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 120, 'Fort', 'කොටුව', 'கோட்டை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 125, 'Galle Face', 'ගාලුමුවදොර', 'காலி முகத்துவாரம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 130, 'Slave Island', 'කොම්පඤ්ඤ වීදිය', '‎கொம்பணித்‎தெரு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 135, 'Hunupitiya', 'හුණුපිටිය', 'ஹுணுப்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 140, 'Suduwella', 'සුදුවැල්ල', 'ஸுது‎வெல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 145, 'Keselwatta', 'කෙසෙල්වත්ත', 'வாழத்‍தோட்டம் (கெஸெல்வத்த)', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 150, 'Panchikawatta', 'පංචිකාවත්ත', 'பஞ்சிக்காவத்தை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 155, 'Maligawatta West', 'මාලිගාවත්ත බටහිර', 'மாலிகாவத்தை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 160, 'Maligakanda', 'මාලිගාකන්ද', 'மாலிகாகந்தை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 165, 'Maradana', 'මරදාන', 'மரதானை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 170, 'Ibbanwala', 'ඉබ්බන්වල', 'இப்பங்‎வெலை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 3, 175, 'Wekanda', 'වෑකන්ද', 'வேகந்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 5, 'Wadulla', 'වඩුල්ල', 'வதுல்லை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 10, 'Sedawatta', 'සේදවත්ත', 'ஸேதவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 15, 'Halmulla', 'හල්මුල්ල', 'ஹல்முல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 20, 'Kotuvila', 'කොටුවිල', 'கொட்டுவில', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 25, 'Veheragoda', 'වෙහෙරගොඩ', '‎வெஹர‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 30, 'Orugodawatta', 'ඔරැගොඩවත්ත', 'ஒறு‎கொடவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 35, 'Meethotamulla', 'මිතොටමුල්ල', 'மீ‎தொட்டமுல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 40, 'Welewatta', 'වැලිවත්ත', '‍‍‍வெ‍‍லேவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 45, 'Kittampahuwa', 'කිටිටන්පහුව', 'கிட்டம்பஹுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 50, 'Wennawatta', 'වැන්නවත්තත', '‎வெண்ணவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 55, 'Maha Buthgamuwa B', 'මහ බත්ගමුව බි', 'மஹ புத்கமுவ B', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 60, 'Kuda Buthgamuwa', 'කුඩා බත්ගමුව', 'குடா புத்கமுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 65, 'Kelanimulla', 'කැළණිමුල්ල', '‎‎கெளணிமுல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 70, 'Ambathale', 'අඔත‍ලේ', 'அம்பத்தலே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 75, 'Mulleriyawa North', 'මුල්ලේරියාව  උතුර', 'முல்லேரியாவ வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 80, 'Belagama', 'බෙලගම', '‍‍பெ‍லேகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 85, 'Kotikawatta East', 'කොටිකාවත්ත  නැගනහිර', '‎கொட்டிகாவத்தை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 90, 'Maha Buthgamuwa A', 'මහ බත්ගමුව ඒ', 'மஹ புத்கமுவ‍ A', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 95, 'Maha Buthgamuwa C', 'මහ බත්ගමුව බි', 'மஹ புத்கமுவ‍ C', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 100, 'Wellampitiya', 'වැල්ලමිපිටිය', '‎வெல்லம்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 105, 'Kuriniyawatta', 'කුරිනියවත්ත', 'குரிநியாவத்‍தை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 110, 'Kolonnawa', 'කොළොන්නාව', '‎கொ‎லொண்ணா‍வை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(6, 115, 'Dahampura', 'දහමිපුර', 'தஹம்பு‍ரை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 120, 'Singhapura', 'සිංහපුර', 'சிங்ஹபு‍ரை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 125, 'Megoda Kolonnawa', 'මිගොඩ කොළොන්නාව', '‎மெகொட ‎கொ‎லொண்ணா‍வ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 130, 'Bopetta', 'බෝපිට', '‍‎‍போ‎பெத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 135, 'Batalandahena', 'බටලන්ද‍හේන', 'பட்டலந்த‍‍‍ஹேண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 140, 'Kotikawatta West', 'කොටිකාවත්ත බටහිර', '‎கொட்டிக்காவத்‍தை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 145, 'Mulleriyawa South', 'මුල්ලේරියාව  දකුණ', 'முள்‍ளேரியா‍வை ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 150, 'Malgama', 'මල්ගම', 'மல்கம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 155, 'Udumulla North', 'උඩුමුල්ල  උතුර', 'உடுமுல்ல வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 160, 'Maligagodella', 'මලිගාගොඩැල්ල', 'மாலிகா‎கொ‎டெல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 165, 'Rajasinghagama', 'රාජසිංහගම', 'ராஜசிங்ஹகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 170, 'Udumulla South', 'උඩුමුල්ල   දකුණ', 'உடுமுள்ள ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 175, 'Himbutana East', 'හිඔුටාන   නැගනහිර', 'ஹிம்புட்டாண கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 180, 'Himbutana West', 'හිඔුටාන   බටහිර', 'ஹிம்புட்டாண ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 185, 'Malpura', 'මල්පුර', 'மல்புர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 190, 'Gothatuwa New Town', 'ගොතටුව නව නගරය', '‎கொத்தட்டுவ புது நகரம்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 195, 'Kajugahawatta', 'කජුගහවත්ත', 'கஜுகஹவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 200, 'Gothatuwa', 'ගොතටුව', '‎கொத்தட்டுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 205, 'Salamulla', 'සලමුල්ල', 'சாலமுல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 210, 'Wijayapura', 'විජයපුර', 'விஜயபுர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 215, 'Gajabapura', 'ගජබාපුර', 'கஜபாபுர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 220, 'Madinnagoda', 'මදින්නගොඩ', 'மாதிண்ண‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 225, 'Elhena', 'ඇල්හේන', 'எல்ஹேண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 6, 230, 'Dodamgahahena', 'දොඩමිගහහේන', '‎தொடம்கஹ்ஹே‍ண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 5, 'Welivita', 'වැලිවිට', '‎வெலிவிட்ட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 10, 'Raggahawatta', 'රග්ගහවත්ත', 'ரக்கஹவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 15, 'Hewagama', 'හේවගම', '‍‍‍‎‍ஹேவாகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 20, 'Kaduwela', 'කඩුවෙල', 'கடு‎வெ‍லை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 25, 'Pahala Bomiriya', 'පහළ බෝමිරිය', 'பஹள ‍‎‍போமிரிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 30, 'Ihala Bomiriya', 'ඉහළ බෝමිරිය', 'இஹள ‍போமிரிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(9, 35, 'Wekewatta', 'වැකේවත්ත', '‍‎‍வே‎கெவிட்ட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 40, 'Nawagamuwa', 'නවගමුව', 'நவகமுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 45, 'Pahala Bomiriya B', 'පහළ බෝමිරිය බි', 'பஹள ‍‎‍போமிரிய B', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 50, 'Welihinda', 'වැලි හින්න', '‎வெலிஹிந்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 55, 'Kothalawala', 'කොතලාවල', '‎கொத்தலாவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 60, 'Mahadeniya', 'මහදෙනිය', 'மஹ‎தெணிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 65, 'Thalahena North', 'තලහේන  උතුර', 'தலஹேண வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 70, 'Malabe North', 'මාළ‍‍ෙඔ  උතුර', 'மால‍பே வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 75, 'Thunadahena', 'තුනදහේන', 'துணடஹேண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 80, 'Korathota', 'කොරතොට', '‎கொர‎‎தொட்ட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 85, 'Nawagamuwa South', 'නවගමුව දකුණ', 'நவகமுவ ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 90, 'Batewela', 'බටේ‍වෙල', 'ப‍‍ட்டே‎வெல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 95, 'Ranala', 'රණාල', 'ரணால', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 100, 'Dedigamuwa', 'දැදිගමුව', '‎தெடிகமுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 105, 'Embilladeniya', 'ඇඔිල්ලදෙනිය', 'எம்பில்லா‎தெணிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 110, 'Welipillewa', 'වැළිපිල්ලැව', '‎‎வெலிபில்‍லேவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 115, 'Shanthalokagama', 'ශාන්තාෙලා්කගම', 'சாந்தா‍லோககம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 120, 'Pore', 'ෙපාෙර්', '‍‍‍‍‍‍‎‍போ‍ரே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 125, 'Malabe East', 'මාළ‍බේ  නැගනහිර', 'மால‍‍‍பே கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 130, 'Malabe West', 'මාල‍බේ බටහිර', 'மால‍‍‍பே ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 135, 'Thalangama North B', 'තලංගම  උතුර', 'தலங்கம வடக்கு B', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 140, 'Thalahena South', 'තලංගම  දකුණ', 'தலா‍ஹேண வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 145, 'Muttettugoda', 'මුත්ෙතටීටු ෙගාඩ', 'முத்‎தெடு‎‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 150, 'Thalangama North A', 'තලංගම  උතුර  ඒ', 'தலங்கம வடக்கு A', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 155, 'Walpola', 'වල්පොල', 'வல்‎பொல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 160, 'Kalapaluwawa', 'කළපලුවාව', 'கலபாலு‎வெவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 165, 'Kotuwegoda', 'කොටුවේගොඩ', '‎‎கொடு‍வே‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 170, 'Subhoothipura', 'සුබුතිපුර', 'சு‍பூதிபுர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 175, 'Udumulla', 'උඩුමුල්ල', 'உடுமுல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 180, 'Battaramulla North', 'බත්තරමුල්ල උතුර', 'பத்தரமுல்ல வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 185, 'Batapotha', 'බටපොත', 'பட‎பொத', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 190, 'Pothuarawa', 'පොතුරාව', '‎பொதுஅரவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 195, 'Hokandara North', 'හෝකන්දර   උතුර', '‍‍‍‍‍‎‍ஹோகந்தர வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 200, 'Oruwala', 'ඔරැවල', 'ஒருவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 205, 'Athurugiriya', 'අතුරුගිරිය', 'அத்துருகிரிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 210, 'Thaldiyawala', 'තල්දියවල', 'தல்டியவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 215, 'Boralugoda', 'බොරලුගොඩ', '‎பொரலு‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 220, 'Hokandara East', 'හෝකන්දර', '‍‍‎‍ஹோகந்தர கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 225, 'Arangala', 'අරංගල', 'அரங்கல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 230, 'Evarihena', 'ඇවරිහේන', 'எவரி‍ஹேண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 235, 'Kumaragewatta', 'කුමාරගේ වත්ත', 'குமார‍கேவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 240, 'Jayawadanagama', 'ජයවධනගම', 'ஜயவடணகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 245, 'Aruppitiya', 'අරැප්පිටිය', 'அருப்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 250, 'Asiri Uyana', 'ආසිරි උයන', 'ஆசிரிஉயண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 255, 'Battaramulla South', 'බත්තරමුල්ල ‍   දකුණ', 'பத்தரமுல்ல ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 260, 'Rajamalwatta', 'රජමල්වත්ත', 'இரஜமல்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 265, 'Pahalawela', 'පහළවෙළ', 'பஹல‎வெல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 270, 'Wickramasinghapura', 'වික්‍රමසිංහපුර', 'விக்கிரமசிங்ஹபுர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 275, 'Wellangiriya', 'වැල්ලන්ගිරිය', '‎வெல்லங்கிரிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 280, 'Hokandara East', 'හෝකන්දර  නැගෙනහිර', '‍‍‎‍ஹோகந்தர ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 9, 285, 'Athurugiriya South', 'අතුරුගිරියදකුණ', 'அத்துருகிரிய ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 5, 'Jalthara', 'ජල්තර', 'ஜல்தர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 10, 'Henpita', 'හෙනේපිට', '‍‎‍ஹேண்பிட்ட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 15, 'Atigala West', 'ආටිගල  බස්නාහිර', 'அடிகல ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 20, 'Atigala East', 'අිටිගල  නැගනහිර', 'அடிகல கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 25, 'Batawala', 'බටවෙල', 'பட்டவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(12, 30, 'Walpita', 'වල්පිට', 'வல்பிட்ட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 35, 'Nawalamulla', 'නාවලමුල්ල', 'நாவலமுல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(12, 40, 'Meegasmulla', 'මිගස්මුල්ල', 'மீகஸ்முல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(12, 45, 'Habarakada North', 'හබරකන්ද  උතුර', 'ஹபரகட வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 50, 'Mullegama North', 'මුල්ලේගම උතුර', 'முல்‍லேகம வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 55, 'Mullegama South', 'මුල්ලේගම දකුණ', 'முல்‍லேகம ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 60, 'Habarakada South', 'හබරකන්ද  දකුණ', 'ஹபரகட ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 65, 'Panagoda Town', 'පනාගොඩ නගරය', 'பணா‎கொடை நகரம்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 70, 'Henawatta', 'හේනවත්ත', '‍ஹேணவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 75, 'Meegoda North', 'මිගොඩ   උතුර', 'மீ‎கொடை வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 80, 'Panaluwa', 'පානලුව', 'பணலுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 85, 'Watareka North', 'වටරැක උතුර', 'வட்ட‍ரேகா வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 90, 'Meegoda South', 'මි‍ගොඩ උතුර   දකුණ', 'மீ‎கொடை ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 95, 'Godagama North', 'ගොඩගම උතුර', '‎கொடகம வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 100, 'Panagoda West', 'පනාගොඩ බස්නාහිර', 'பணா‎கொடை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 105, 'Panagoda East', 'පනාගොඩ නැගනහිර', 'பணா‎கொடை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 110, 'Habarakada Watta', 'හබරකඩ වත්ත', 'ஹபரகட வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 115, 'Homagama North', 'හෝමාගම උතුර', '‍‎‍ஹோமாகம வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 120, 'Homagama West', 'හෝමාගම  බස්නාහිර', '‍‎‍ஹோமாகம ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 125, 'Homagama South', 'හෝමාගම  දකුණ', '‍‎‍ஹோமாகம ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 130, 'Galavilawatta North', 'ගලවිලවත්ත  උතුර', 'கலவிலவத்த  வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 135, 'Homagama Town', 'හෝමාගම නගරය', '‍‎‍ஹோமாகம நகரம்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 140, 'Homagama East', 'හෝමාගම නැගනහිර', '‍‎‍ஹோமாகம கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 145, 'Pitipana Town', 'පිටිපන නගරය', 'பிட்டிபண நகரம்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 150, 'Godagama South', 'ගොඩගම  දකුණ', '‎கொடகம ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 155, 'Kurunduwatta', 'කුරැදුවත්ත', 'குருந்துவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 160, 'Gehenuwala', 'ගේනලුව', '‎கெ‎ஹெணுவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 165, 'Watareka South', 'වටරැක දකුණ', 'வட்ட‍ரேகா ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 170, 'Ovitigama', 'ඕවිටිගම', 'ஓவிட்டிகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 175, 'Kandanawatta', 'කන්දනවත්ත', 'கந்தானவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 180, 'Kiriberiyakele', 'කිරිබෙරියකැළේ', 'கிரி‎பெரிய‎கெ‍லே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 185, 'Mawathgama', 'මහාවතගම', 'மாவத்கம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 190, 'Katuwana', 'කටුවාන', 'கட்டுவான', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 195, 'Galavilawatta South', 'ගලවිලවත්ත දකුණ', 'கலவிலவத்த ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 200, 'Niyandagala', 'නියන්දගල', 'நியந்தகல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 205, 'Hiripitiya', 'හිරිපිටිය', 'ஹிறிபிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 210, 'Mambulgoda', 'මාම්බුල්ගොඩ', 'மாம்புல்‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 215, 'Kithulhena', 'කිතලුහේන', 'கித்துல்‍ஹேண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 220, 'Siddamulla North', 'සිද්ධමුල්ල    උතුර', 'சித்தமுல்ல வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 225, 'Siddamulla South', 'සිද්ධමුල්ල දකුණ', 'சித்தமுல்ல ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 230, 'Mattegoda West', 'මට්ටේ', 'மத்‍தே‎கொட ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 235, 'Mattegoda Central ''A''', '', 'மத்திய மத்‍தே‎கொட ''A''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 240, 'Mattegoda East', '', 'மத்‍தே‎கொட கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 245, 'Brahmanagama', '', 'பிராமணகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 250, 'Deepangoda', 'ධිපාන්ගොඩ', 'தீபாங்‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 255, 'Magammana West', 'මාගම්මන  බස්නාහිර', 'மாகம்மண ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 260, 'Magammana East', 'මාගම්මන නැගනහිර', 'மாகம்மண கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 265, 'Uduwana', 'උධුවන', 'உடுவண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 270, 'Prasannapura', 'ප්‍රසන්නපුර', 'பிரசண்ணபுர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 275, 'Pitipana North', 'ප්‍රසන්නපුර උතුර', 'பிட்டிபண வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 280, 'Suwapubudugama', 'සුවපුබුදුගම', 'சுவபுபுதுகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 285, 'Pitipana South', 'පිටිපන   දකුණ', 'பிட்டிபண ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 290, 'Dolahena', 'දොළහේන', '‎தொல‍ஹேண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 295, 'Diyagama East', 'දියගම  නැගනහිර', 'தியகம கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 300, 'Diyagama West', 'දියගම බස්නාහිර', 'தியகம ‍‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 305, 'Kirigampamunuwa', 'කිරිගම්පමුනුව', 'கிரிகம்பமுணுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 310, 'Mattegoda Central B', '', 'மத்திய மத்தே‎கொட '' B ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 315, 'Siyambalagoda North', 'සියබලාගොඩ    උතුර', 'சியம்பலா‎கொட வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 320, 'Kudamaduwa', 'කුඩමධුව', 'குடாமடுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 325, 'Sangharama', '', 'சங்கஹராம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 330, 'Siyambalagoda South', 'සියඔලාගොඩ   දකුණ', 'சியம்பலா‎கொட ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 335, 'Rilawala', '', 'ரிலாவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 340, 'Kahathuduwa West', 'කහතුඩුව  බස්නාහිර', 'கஹதுடுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 345, 'Kiriwattuduwa South', 'කිරිවත්තුඩුව   දකුණ', 'கிரிவத்துடுவ ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 350, 'Kiriwattuduwa North', 'කිරිවත්තුඩුව උතුර', 'கிரிவத்துடுவ வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 355, 'Moonamale ,  Yakahaluwa', 'මුණමලේ,  යකහලුව', 'மூணம‍லே ,  யக்காஹலுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 360, 'Kithulavila', 'කිතුලවිල', 'கித்துலவில', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 365, 'Kahathuduwa North', 'කහතුඩුව  උතුර', 'கஹதுடுவ வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 370, 'Kahathuduwa East', 'කහතුඩුව  බස්නාහිර', 'கஹதுடுவ கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 375, 'Kahathuduwa South', 'කහතුඩුව   දකුණ', 'கஹதுடுவ ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 380, 'Undurugoda', '', 'உந்துரு‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 385, 'Wethara', 'වැතර', '‍‎‍வேதர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 390, 'Ambalangoda', 'අම්බලන්ගොඩ', 'அம்பலாங்‎கொடை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 395, 'Heraliyawala', 'හිරලියාවෙල', '‎ஹெரலியவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 400, 'Palagama', 'පාලගම', 'பாலகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 12, 405, 'Weniwelkola', 'වැනිවල්කොල', '‎வெணி‎வெல்‎கொல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 5, 'Bollathawa', 'ෙබාල්ලතව', '‍‎‍போலதவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 10, 'Kanampella West', 'කනම්පැල්ල    බස්නාහිර', 'கணம்‎பெல்ல ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 15, 'Kanampella East', 'කනම්පැල්ල   නැගනහිර', 'கணம்‎பெல்ல கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 20, 'Manakada', 'මනකඩ', 'மணகட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 25, 'Eswatta North', 'ඇස්වත්ත  උතුර', 'எஸ்வத்த வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 30, 'Kiriwandala North', 'කිරිවන්දල   උතුර', 'கிரிவந்தல வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 35, 'Kudagama', 'කුඩාගම', 'குடாகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 40, 'Weralupitiya', 'වෙිරලුපිටිය', '‍‎‍வேறலுபிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 45, 'Seethagama', 'සිතගම', 'சீதாகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 50, 'Avissawella', 'අවිස්සාවේල්ල', 'அவிஸ்சா‎வெல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 55, 'Ukwatta', 'උක්වත්ත', 'உக்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 60, 'Agra Pedesa', 'අග්රා ෙපෙදස', 'ஆக்ர ‎பெ‍தேச', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 65, 'Eswatta South', 'ඇස්වත්ත දකුණ', 'எஸ்வத்த ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 70, 'Ihala Kosgama North', 'ඉහළ කොස්ගම උතුර', 'இஹல ‎கொஸ்கம வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 75, 'Thawalgoda', 'තවල්ගොඩ', 'தவல்‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 80, 'Muruthagama', 'මුරැතගම', 'முருத்தகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 85, 'Akaravita', 'අකරවිට', 'அகரவிட்ட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 90, 'Kahatapitiya', 'කහටපිටිය', 'கஹடபிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 95, 'Kalu Aggala', 'කලු අග්ගල', 'களு அக்கல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 100, 'Salawa', 'සාලාව', 'சாலாவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 105, 'Pahala Kosagama West', 'පහළ කොස්ගම   බස්නාහිර', 'பஹல ‎‎கொஸ்கம ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 110, 'Pahala Kosgama East', 'පහළ කොස්ගම නැගනහිර', 'பஹல ‎‎கொஸ்கம கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 115, 'Ihala Kosgama South', 'ඉහළ කොස්ගම  දකුණ', 'இஹல ‎‎கொஸ்கம ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 120, 'Miriswatta', 'මිරිස්වත්ත', 'மிரிஸ்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 125, 'Aluth Ambalama', 'අලුත් අමබලම', 'அளுத் அம்பலம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 130, 'Kiriwandala South', 'කිරිවන්දල  දකුණ', 'கிரிவந்தல ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 135, 'Kotahera', 'කොටහේර', '‎கொட்ட‍‍ஹேற', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 140, 'Seethawaka', 'සිතාවක', 'சீதாவக்க', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 145, 'Aradhana Kanda', 'අරදන්කඩවල', 'அரதாண கந்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 150, 'Puwakpitiya South', 'පුවක්පිටිය  දකුණ', 'புவக்பிட்டிய ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 155, 'Puwakpitiya', 'පුවක්පිටිය', 'புவக்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 160, 'Egodagama', 'එගෙ‍ාඩගම', 'எ‎கொடகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 165, 'Weragolla North', 'විරගෙලේල උතුර', '‍‎‍வேர‎கொல்ல வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 170, 'Hingurala', 'හිගුරල', 'ஹிங்குரால', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 175, 'Kadugoada North', 'කඩුගෙඩෙ  උතුර', 'கடு‎கொஅட வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 180, 'Mawalgama', 'මාවල්ගම', 'மவல்கம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 185, 'Suduwella', 'සුදුවැල්ල', 'சுது‎வெல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 190, 'Gira Imbula', 'ගිරා ඉඔුළ', 'கிரி இம்புல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 195, 'Walauwathta', 'වලවීවත්ත', 'வலவ்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 200, 'Pahala Hanwella', 'පහළ හංවැල්ල', 'பஹல ஹங்‎வெல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 205, 'Hanwella Town', 'හංවැල්ල නගරය', 'ஹங்‎வெல்ல நகரம்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 210, 'Ihala Hanwella North', 'ඉහළ  හංවැල්ල උතුර', 'இஹல ஹங்‎வெல்ல வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 215, 'Niripola', 'නිරිපොළ', 'நிரி‎பொல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 220, 'Brandigampala', 'බ්‍රැන්ඩිගම්පළ', 'பிரண்டிகம்பல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 225, 'Kadugoda South', 'කඩුගොඩ   දකුණ', 'கடு‎கொட ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 230, 'Weragolla South', 'වේරගොල්ල   දකුණ', '‍‎‍வேர‎கொல்ல தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 235, 'Digana', 'දිගන', 'திகண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 240, 'Lahirugama', 'ලහිරුගම', 'லஹிருகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 245, 'Mambula', 'මාම්බුල', 'மாம்புல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 250, 'Welikanna', 'වැලිකත්න', '‎வெலிகண்ண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 255, 'Kahahena', 'කහහේන', 'கஹ‍ஹேண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 260, 'Neluwattuduwa', 'නෙලුවත්තුඩුව', '‎நெலுவத்துடுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 265, 'Diddeniya North', 'දිදිදෙනිය   උතුර', 'தித்‎தெணிய வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 270, 'Ihala Hanwella South', 'ඉහළ හංවැල්ල  දකුණ', 'இஹல ஹங்‎வெல்ல ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 275, 'Pahathgama', 'පහත්ගම', 'பஹத்கம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 280, 'Jayaweeragoda', 'ජය විර්යගොඩ', 'ஜயவீர‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 285, 'Koodaluvila', 'කුඩලුවිල', 'கூடலுவில', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 290, 'Thunnana East', 'තුන්තාන නැගනහිර', 'துண்ணண கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 295, 'Diddeniya South', 'දිද්දෙනිය  දකුණ', 'தித்‎தெணிய ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 300, 'Elamalawala', 'ඒළමලවල', 'எலமலவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 305, 'Ilukovita', 'ඉලුකුවිට', 'இலு‍கோவிட்ட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 310, 'Koswatta', 'කොස්වත්ත', '‎கொஸ்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 315, 'Pagngnagula', 'පඣඣාගුල', 'பங்ஞாணகுல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 320, 'Pelpola', 'පැල්පොළ', '‎பெல்‎பொல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 325, 'Kudakanda', 'කුඩාකන්ද', 'குடாகந்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 330, 'Thunnana West', 'තුන්තාත බටහිර', 'துண்ணண ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 335, 'Mawathagama West', 'මාවතගම බටහිර', 'மாவத்தகம ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 15, 340, 'Mawathagama East', 'මාවතගම නැගනහිර', 'மாவத்தகம கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 5, 'Pinnawala North', 'පින්නවල උතුර', 'பிண்ணவல  வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 10, 'Pinnawala South', 'පින්නවල  දකුණ', 'பிண்ணவல ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 15, 'Waga North', 'වග උතුර', 'வக வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 20, 'Waga East', 'වග නැගනහිර', 'வக கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 25, 'Thummodara', 'තුම්මෝදර', 'தும்‍மோதர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 30, 'Waga South', 'වග දකුණ', 'வக ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 35, 'Siyambalawa', 'සියඔලාව', 'சியம்பலாவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 40, 'Pahala Bope', 'පහළ බෝපේ', 'பஹல ‍போ‍பே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 45, 'Halpe', 'හල්පේ', 'ஹல்‍பே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 50, 'Waga West', 'වග බටහිර', 'வக ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 55, 'Uggalla', 'උග්ගල්ල', 'அக்கல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 60, 'Wewelpanawa', 'වේවැල්පනාව', '‍‎‍வே‎வெல்பணாவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 65, 'Pitumpe North', 'පිටුමිපේ  උතුර', 'பிதும்‍பே வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 70, 'Pitumpe South', 'පිටුමිපේ දකුණ', 'பிதும்‍பே ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 75, 'Galagedara East', 'ගළගෙදර නැගකහිර', 'கல‎கெதர கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 80, 'Galagedara North', 'ගළගෙදර  උතුර', 'கல‎கெதர வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 85, 'Galagedara South', 'ගළගෙදර  දකුණ', 'கல‎கெதர ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 90, 'Padukka', 'පාදුක්ක', 'பாதுக்கை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 95, 'Arukwatta North', 'අරැක්වත්ත  උතුර', 'அருக்வத்த வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 100, 'Arukwatta South', 'අරැක්වත්ත   දකුණ', 'அருக்வத்த ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 105, 'Ganegoda', 'ගනේගොඩ', 'க‍ணே‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 110, 'Angampitiya', 'අන්ගම්පිටිය', 'அங்கம்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 115, 'Weragala', 'වේරගළ', '‍‎‍வேறகல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 120, 'Angamuwa', 'අන්ගමුව', 'அங்கமுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 125, 'Udumulla', 'උඩුමුල්ල', 'உடுமுள்ள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 130, 'Poregedara', 'පොරෙිගෙදර', '‍‍‎‍போ‎ரெ‎கெதர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES(18, 135, 'Pahala Padukka', 'පහළ පාදුක්ක', 'பஹல பாதுக்கை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 140, 'Liyanwala', 'ලියත්වල', 'லியண்வல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 145, 'Kurugala', 'කුරැගල්ල', 'குருகல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 150, 'Madulawa South', 'මඩුවල දකුණ', 'மாதுலவ ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 155, 'Madulawa North', 'මඩුවල  උතුර', 'மாதுலவ வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 160, 'Horakandawala', 'හොරකන්දවෙල', 'ஹொரகந்தவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 165, 'Dampe', 'දාම්පේ', 'தம்‍பே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 170, 'Beruketiya', 'බේරැකැටිය', '‎பெரு‎கெட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 175, 'Horagala West', 'හොරගල  බටහිර', '‎ஹொறகல ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 180, 'Horagala East', 'හොරගල   නැගකහිර', '‎ஹொறகல கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 185, 'Beliattavila', 'බෙලිඅත්තවිළ', '‎பெலியத்தவில', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 190, 'Miriyagalla', 'මිරියන්ගල්ල', 'மீரியாகல்ல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 195, 'Malagala', 'මලගළ', 'மலகல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 200, 'Kahawala', 'කහවළ', 'கஹவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 205, 'Yatawathura', 'යටවතුර', 'யட்டவத்துர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 210, 'Mahingala', 'මාහින්ගල්ල', 'மஹிங்கல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 215, 'Ihala Bope', 'ඉහළ බෙි්පේ', 'இஹல ‍போ‍பே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 220, 'Gurulana', 'ගුරැලන', 'குருலாண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 225, 'Udagama', 'උඩගම', 'உடுகம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 18, 230, 'Dambora', 'දම්බොර', 'தம்‍போர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 5, 'Mirihana South', 'මිරිහාන දකුණ', 'மிறிஹாண ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 10, 'Mirihana North', 'මිරිහාන    උතුර', 'மிறிஹாண வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 15, 'Madiwela', 'මාදිවෙල', 'மாதி‎வெல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 20, 'Thalawathugoda West', 'තළවතුගොඩ බටහිර', 'தளவத்து‎கொட ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 25, 'Thalawathugoda East', 'තළවතුගොඩ  නැගනහිර', 'தளவத்து‎கொட கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 30, 'Kalalgoda', 'කළල්ගොඩ', 'கலல்‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 35, 'Kottawa East', 'කොට්ටාව නැගනහිර', '‎கொட்டாவ கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 40, 'Rukmale West', 'රුක්මළේ   බටහිර', 'ருக்ம‍லே ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 45, 'Rukmale East A', 'රැක්මළේ  නැගනහිර   ඒ', 'ருக்ம‍லே கிழக்கு '' A ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 50, 'Rukmale East B', 'රුක්මළේ නැගනහිර  බි', 'ருக்ம‍லே கிழக்கு '' B ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 55, 'Liyanagoda', 'ලියනගොඩ', 'லியண‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 60, 'Kottawa North', 'කොට්ටාව  උතුර', '‎கொட்டாவை வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 65, 'Depanama', 'දෙපානම', '‎தெபாணம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 70, 'Polwatta', 'පොල්වත්ත', '‎பொல்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 75, 'Pamunuwa', 'පමුණුව', 'பமுணுவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 80, 'Thalapathpitiya', 'තළපත්පිටිය', 'தளபத்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 85, 'Pragathipura', 'ප්‍රගතිපුර', 'பிரகதிபுர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 90, 'Udahamulla East', 'උඩහාමුල්ල  නැගනහිර', 'உடஹமுள்ள கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 95, 'Udahamulla West', 'උඩහාමුල්ල   බටහිර', 'உடஹமுள்ள ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 100, 'Pathiragoda', 'පති‍රේගොඩ', 'பத்திரா‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 105, 'Maharagama East', 'මහරගම  නැගනහිර', 'மஹரகம கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 110, 'Maharagama West', 'මහරගම    බටහිර', 'மஹரகம ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 115, 'Dambahena', 'දඔහේන', 'தம்ப‍ஹேண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 120, 'Pannipitiya North', 'පන්නිපිටිය උතුර', 'பண்ணிபிட்டிய வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 125, 'Kottawa West', 'කොට්ටාව   බටහිර', '‎கொட்டாவை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 130, 'Kottawa South', 'කොට්ටාව දකුණ', '‎கொட்டாவை ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 135, 'Malapalla West', 'මලපල්ල   බටහිර', 'மலபல்ல ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 140, 'Malapalla East', 'මලපල්ල   නැගනහිර', 'மலபல்ல கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 145, 'Makumbura North', 'මාකුඔුර    උතුර', 'மாகும்புர வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 150, 'Makumbura South', 'මාකුඔුර    දකුණ', 'மாகும்புர ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 155, 'Kottawa Town', 'කොට්ටාව නගරය', '‎கொட்டாவை நகரம்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 160, 'Pannipitiya South', 'පන්නිපිටිය  දකුණ', 'பண்ணிபிட்டிய ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 165, 'Maharagama Town', 'මහරගම නගරය', 'மஹரகம நகரம்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 170, 'Godigamuwa South', 'ගොඩිගමුව  දකුණ', '‎கொடிகமுவ ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 175, 'Godigamuwa South B', 'ගොඩිගමුව දකුණ බි', '‎கொடிகமுவ ‎தெற்கு '' B ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 180, 'Godigamuwa North', 'ගොඩිගමුව උතුර', '‎கொடிகமுவ வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 190, 'Navinna', 'නාවින්න', 'நாவிண்ண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 195, 'Wijerama', 'විජේරාම', 'வி‍ஜேராம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 200, 'Gangodavila South B', 'ගනේගොඩවිළ  දකුණ බි', 'கங்‎கொடவில ‎தெற்கு B', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 21, 205, 'Jambugasmulla', 'ජම්ඔුගස්මුල්ල', 'ஜம்புகஸ்முள்ள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 5, 'Obesekarapura', 'ඔබේසේකරපුර', 'ஒ‍‍பே‍சேகரபுர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 10, 'Welikada West', 'වැළිකඩ බටහිර', '‎வெலிகட ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 15, 'Welikada East', 'වැළිකඩ නැගනහිර', '‎வெலிகட கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 20, 'Rajagiriya', 'රාජගිරිය', 'ராஜகிரிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 25, 'Welikada North', 'වැළිකඩ උතුර', '‎வெலிகட வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 30, 'Nawala East', 'නාවල නැගනහිර', 'நவைளை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 35, 'Koswatta', 'කොස්වත්ත', '‎கொஸ்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 40, 'Ethulkotte West', 'ඇතුළ්කොට්ටේ බටහිර', 'எத்துள்‍கோட்‍டே ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 45, 'Ethulkotte', 'ඇතුළ්කොට්ටේ', 'எத்துள்‍கோட்‍டே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 50, 'Pitakotte East', 'පිටකොට්ටේ  නැගනහිර', 'பிட்ட‍கோட்‍டே கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 55, 'Pitakotte', 'පිටකොට්ටේ', 'பிட்ட‍கோட்‍டே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 60, 'Pitakotte West', 'පිටකොට්ටේ බටහිර', 'பிட்ட‍கோட்‍டே ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 65, 'Nawala  West', 'නාවළ බටහිර', 'நாவளை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 70, 'Nugegoda West', 'නුගේගොඩ  බටහිර', 'நு‍கே‎கொடை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 75, 'Pagoda', 'පා‍ගොඩ', 'பா‎கொட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 80, 'Nugegoda', 'නුගේගොඩ', 'நு‍கே‎கொடை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 85, 'Pagoda East', 'පා‍ගොඩ  නැගනහිර', 'பா‎கொட கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 90, 'Gangodavila North', 'ගංගොඩවිළ උතුර', 'கங்‎கொடவில வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 95, 'Gangodavila South', 'ගංගොඩවිළ   දකුණ', 'கங்‎கொடவில ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 24, 100, 'Gangodavila East', 'ගංගොඩවිළ  නැගනහිර', 'கங்‎கொடவில கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 5, 'Kollupitiya', 'කුලියාපිටිය', '‎கொள்ளுப்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 10, 'Bambalapitiya', 'බම්බළපිටිය', 'பம்பலப்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 15, 'Kurunduwatta', 'කුරැදුවත්ත', 'கருவாத்‍தோட்டம்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 20, 'Kuppiyawatta West', 'කුප්පියවත්ත බටහිර', 'குப்பியாவத்த ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 25, 'Kuppiyawatta East', 'කුප්පියවත්ත  නැගනහිර', 'குப்பியாவத்த கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 30, 'Dematagoda', 'දෙමටගොඩ', '‎தெமட்ட‎கொடை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 35, 'Wanathamulla', 'වන්තමුල්ල', 'வனாத்தமுள்ள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 40, 'Borella North', 'බොරැල්ල උතුර', '‎பொரளை வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 45, 'Borella South', 'බොරැල්ල දකුණ', '‎பொரளை ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 50, 'Gothamipura', 'ගොතමිපුර', '‍‎‍கோதமிபுர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 55, 'Narahenpita', 'නාරන්පිට', 'நாரா‍ஹேன்பிட்ட', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 60, 'Thimbirigasyaya', 'කිඔිරිගස්යාය', 'திம்பிரிகஸ்யாய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 65, 'Milagiriya', 'මිල්ගිරිය', 'மிலாகிரிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 70, 'Havelock Town', 'හැවිලොක් නගරය', '‍‎‎‍‍‍ஹேவ்‎லொக் டவுன்', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 75, 'Kirula', 'කිරැළ', 'கிரு‍ள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 80, 'Kirulapone', 'කිරැළපණ', 'கிரு‍ளப்பண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 85, 'Wellawatta North', 'වැල්ලවත්ත උතුර', '‎வெல்லவத்தை வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 90, 'Wellawatta South', 'වැල්ලවත්ත දකුණ', '‎வெல்லவத்தை ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 95, 'Pamankada West', 'පමාන්කඩ බටහිර', 'பாமண்கடை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 27, 100, 'Pamankada East', 'පමාන්කඩ   නැගනහිර', 'பாமண்கடை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 5, 'Sri Saranankara', 'සිරි සරණංකර', 'ஸ்ரீ சரணங்கார', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 10, 'Vilawala', 'විළවළ', 'விலவல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 15, 'Dutugemunu', 'දුටුගැමුණු', 'துட்டு‎கெமுணு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 20, 'Kohuwala', 'කොහුවළ', '‎கொஹுவலை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 25, 'Kalubovila', 'කලුබෙ‍ා්විළ', 'களு‍போவிலை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 30, 'Hathbodhiya', 'හත්බෝධිය', 'ஹத்‍போதிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 35, 'Galwala', 'ගල්වළ', 'கல்வள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 40, 'Dehiwala West', 'දෙහිවල බටහිර', '‎தெஹிவளை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 45, 'Dehiwala East', 'දෙහිවල නැගනහිර', '‎தெஹிவளை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 50, 'Udyanaya', 'උද්‍යානය', 'உத்யாணய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 55, 'Nedimala', 'නෙදිමල', '‎நெதிமால', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 60, 'Malwatta', 'මල්වත්ත', 'மல்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 65, 'Jayathilaka', 'ජයතිලක', 'ஜயதிலக்க', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 70, 'Karagampitiya', 'කරගම්පිටිය', 'கரகம்பிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 30, 75, 'Kawdana East', 'කව්ඩක බටහිර', 'கவ்டாணா கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 5, 'Mount Lavinia', 'මවුන්ටීලැෙවීනියා', 'கல்கிஸ்ஸை', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 10, 'Kawdana West', 'කවුඩන බටහිර', 'கவ்டாணா ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 15, 'Watarappala', 'වටරප්පළ', 'வட்டராப்பல', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 20, 'Wathumulla', 'වතුමුල්ල', 'வத்துமுள்ள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 25, 'Katukurunduwatta', 'කටුකුරැකන්ද', 'கட்டுகுருந்துவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 30, 'Attidiya North', 'ඇටිදිය උතුර', 'அத்திடிய வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 35, 'Attidiya South', 'ඇටිදිය දකුණ', 'அத்திடிய ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 40, 'Piriwena', 'පිරිවෙන', 'பிரி‎வெண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 45, 'Wedikanda', 'වැදිකන්ද', '‎வெடிகந்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 50, 'Vihara', 'විහාර', 'விஹார‍', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 55, 'Rathmalana West', 'රත්මලාන බටහිර', 'இரத்மளாணை ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 60, 'Rathmalana East', 'රත්මලාන  නැගනහිර', 'இரத்மளாணை கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 31, 65, 'Kandawala', 'කන්දවල', 'கந்தவள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 5, 'Angulana North', 'අගුලාන උතුර', 'அங்குலாண வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 10, 'Kaldemulla', 'කල්දිමුල්ල', 'கல்‎தெமுள்ள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 15, 'Soysapura North', 'සොයියාපුර දකුණ', '‎சொய்சாபுர வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 20, 'Soysapura South', 'සොයියාපුර  උතුර', '‎சொய்சாபுர ‎‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 25, 'Dahampura', 'දහම්පුර', 'தஹம்புர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 30, 'Thelawala North', '‍තෙලවල උතුර', '‎தெளவல வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 35, 'Borupana', 'බොරුපණ', '‎பொருபண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 40, 'Thelawala South', 'කෙළවල දකුණ', '‎தெளவல  ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 45, 'Lakshapathiya North', 'ලක්ෂපතිය  උතුර', 'லக்க்ஷபதிய வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 50, 'Lakshapathiya Central', 'ලක්ෂපතිය   මධ්‍යම', 'லக்க்ஷபதிய மத்திய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 55, 'Angulana South', 'අගුළාන දකුණ', 'அங்குலாண ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 60, 'Uyana South', 'උයන දකුණ', 'உயண ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 65, 'Uyana North', 'උයන    උතුර', 'உயண வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 70, 'Rawathawatta South', 'රාවතාවත්ත දකුණ', 'ராவத்தாவத்த ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 75, 'Rawathawatta East', 'රාවතාවත්ත  නැගනහිර', 'ராவத்தாவத்த கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 80, 'Lakshapathiya South', 'ලක්ෂපතිය දකුණ', 'லக்க்ஷபதிய ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 85, 'Kaduwamulla', 'කඩුවමුල්ල', 'கடுவமுள்ள', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 90, 'Katubedda', 'කටුබැද්ද', 'கட்டு‎பெத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 95, 'Molpe', 'මුල්පේ', '‍‎‍மோல்‍பே', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 100, 'Moratumulla North', 'මොරටු මුල්ල උතුර', '‎மொறட்டுமுள்ள வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 105, 'Kadalana', 'කඩළාන', 'கடலாண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 110, 'Rawathawatta West', 'රාවත්තේවට  බටහිර', 'ராவத்தாவத்த ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 115, 'Idama', 'ඉඩම', 'இடம', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 120, 'Uswatta', 'උස්වත්ත', 'உஸ்வத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 125, 'Moratumulla South', 'මොරටු මුල්ල දකුණ', '‎மொறட்டுமுள்ள ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 130, 'Indibedda West', 'ඉන්දිබැඩිද බටහිර', 'இந்தி‎பெத்த ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 135, 'Moratumulla East', 'මොරටු මුල්ල   නැ‍‍ගෙනහිර', '‎மொறட்டுமுள்ள கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 140, 'Moratumulla West', 'මොරටු මුල්ල  බටහිර', '‎மொறட்டுமுள்ள ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 145, 'Villorawatta East', 'විල්ලුරවත්ත   නැගනහිර', 'வில்‎லொறவத்த கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 150, 'Villorawatta West', 'විල්ෙලා්ර වත්ත  බටහිර', 'வில்‎லொறவத்த ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 155, 'Indibedda East', 'ඉදිබැද්ද  නැෙගනහිර', 'இந்தி‎பெத்த கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 160, 'Moratuwella North', 'මොරටු වැල්ල උතුර', '‎மொறட்டு‎வெல வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 165, 'Moratuwella West', 'මොරටු වැල්ල බටහිර', '‎மொறட்டு‎வெல ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 170, 'Koralawella North', 'කොරළවෙළ', '‍‎‍கோறல‎வெள வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 175, 'Koralawella Eest', 'කොරළවැල්ල නැගනහිර', '‍‎‍கோறல‎வெள கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 180, 'Koralawella West', 'කොරළවැල්ල  බටහිර', '‍‎‍கோறல‎வெள ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 185, 'Koralawella South', 'කොරළවැල්ල දකුණ', '‍‎‍கோறல‎வெள ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 190, 'Katukurunda North', 'කටුකුරැන්ද  උතුර', 'கட்டுகுருந்த வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 195, 'Katukurunda South', 'කටුකුරැන්ද   දකුණ', 'கட்டுகுருந்த ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 200, 'Egoda Uyana North', 'ඒගොඩ උයන උතුර', 'எ‎கொட உயண வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 205, 'Egoda Uyana Central', 'ඒගොඩ උයන මධ්‍යම', 'மத்திய எ‎கொட உயண', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 33, 210, 'Egoda Uyana South', 'ඒගොඩ උයන දකුණ', 'எ‎கொட உயண ‎தெற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 5, 'Pepiliyana West', 'පැපිලියාන බටහිර', '‎பெப்பிலியாண ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 10, 'Pepiliyana East', 'පැපිලියාන නැගනහිර', '‎பெப்பிலியாண கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 15, 'Divulpitiya East', 'දිවුල්පිටිය   නැගනහිර', 'திவுள்பிட்டிய கிழக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 20, 'Divulpitiya West', 'දිවුල්පිටිය  බටහිර', 'திவுள்பிட்டிய ‍மேற்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 25, 'Bellanvila', 'බෙල්ලන්විල', '‎பெல்லண்வில', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 30, 'Boralesgamuwa West A', 'බොරලැස්ගමුව  බටහිර  ඒ', '‎பொரலஸ்கமுவ ‍மேற்கு '' A ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 35, 'Boralesgamuwa West C', 'බොරලැස්ගමුව බටහිර සි', 'பொரலஸ்கமுவ ‍மேற்கு '' C ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 40, 'Rattanapitiya', 'රතනපිටිය', 'இரத்தணபிட்டிய', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 45, 'Egodawatta', 'අගොඩවත්ත', 'எ‎கொடவத்த', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 50, 'Boralesgamuwa East A', 'බොරලැස්ගමුව  නැගනහිර  ඒ', 'பொரலஸ்கமுவ கிழக்கு '' A ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 55, 'Boralesgamuwa West B', 'බොරලැස්ගමුව බටහිර  බි', 'பொரலஸ்கமுவ ‍மேற்கு '' B ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 60, 'Werahera North', 'වේරහැර උතුර', '‍வேர‍ஹேர வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 65, 'Boralesgamuwa East B', 'බොරලැස්ගමුව නැගනහිර  බි', 'பொரலஸ்கமுவ கிழக்கு '' B ''', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 70, 'Neelammahara', 'නිල්ලමිමහර', 'நீலம்மஹர', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 75, 'Katuwawala North', 'කටුවාවෙල   උතුර', 'கட்டுவாவள வடக்கு', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 80, 'Vishwakalawa', 'විස්වකළාව', 'விஷ்வகலாவ', 1 );
INSERT INTO COMMON.GN_DIVISIONS (dsDivisionUKey , gnDivisionId, enGNDivisionName, siGNDivisionName, taGNDivisionName , active)  VALUES( 36, 85, 'Werahera South', 'වේරහැර උතුර', '‍வேர‍ஹேர ‎தெற்கு', 1 );