INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(11, 'කොළඹ', 'Colombo', '‎கொழும்பு');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(12, 'ගම්පහ', 'Gampaha', 'கம்‍‍‎ப‍‍ஹ');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(13, 'කළුතර', 'Kalutara', 'களுத்து‍றை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(21, 'මහනුවර', 'Kandy', 'கண்டி');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(22, 'මාතලේ', 'Matale', 'மாத்த‍‍‍ளை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(23, 'නුවරඑළිය', 'Nuwara Eliya', 'நுவ‎ரெளியா');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(31, 'ගාල්ල', 'Galle', 'காலி');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(32, 'මාතර', 'Matara', 'மாத்தறை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(33, 'හම්බන්තොට', 'Hambantota', 'ஹம்பாந்தோட்‍டை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(41, 'යාපනය', 'Jaffna', 'யாழ்பாணம்');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(42, 'මන්නාරම', 'Mannar', 'மன்னார்');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(43, 'වව්නියාව', 'Vavuniya', 'வவுனியா');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(44, 'මුලතිව්', 'Mullaitivu', 'முள்ளைத்தீவு');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(45, 'කිලිනොච්චි', 'Kilinochchi', 'கிளி‎‎நொச்சி');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(51, 'මඩකලපුව', 'Batticaloa', 'மட்டக்களப்பு');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(52, 'අම්පාර', 'Ampara', 'அம்பா‍‍றை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(53, 'ත්‍රිකුණාමලය', 'Trincomalee', 'திரு‍கோண‍மலை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(61, 'කුරුණෑගල', 'Kurunegala', 'குருணாக‍லை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(62, 'පුත්තලම', 'Puttalam', 'புத்தளம்');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(71, 'අනුරාධපුරය', 'Anuradhapura', 'அநுராதபுரம்');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(72, 'පොළොන්නරුව', 'Polonnaruwa', '‎பொலண்ணரு‍வை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(81, 'බදුල්ල', 'Badulla', 'பது‍ளை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(82, 'මොනරාගල', 'Moneragala', '‎மொணராக‍லை');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(91, 'රත්නපුර', 'Ratnapura', 'இரத்திணபுரி');
INSERT INTO COMMON.DISTRICTS (districtId, siDistrictName, enDistrictName, taDistrictName)  VALUES(92, 'කෑගල්ල', 'Kegalle', '‍‎‍‍‍கேகா‍லை');

INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 3, 'කොළඹ', 'Colombo', 'கொழும்பு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 6, 'කොළොන්නාව', 'Kolonnawa', 'கொ‎லொண்ணா‍வை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 9, 'කඩුවෙළ', 'Kaduwela', 'கடு‎வெ‍லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 12, 'හෝමගම', 'Homagama', 'ஹோமாகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 15, 'හංවැල්ල', 'Hanwella', 'ஹங்‎வெல்‍லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 18, 'පාදුක්ක', 'Padukka', 'பாதுக்‍கை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 21, 'මහරගම', 'Maharagama', 'மஹரகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 24, 'ශ්‍රී ජයවර්ධනපුර කෝට්ටෙ', 'Sri Jayawardanapura Kotte', 'ஸ்ரீ ஜயவர்தணபுர ‍கோட்‍டை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 27, 'තිඹිරිගස්යාය', 'Thimbirigasyaya', 'திம்பிரிகஸ்யா‍யை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 30, 'දෙහිවල -ගල්කිස්ස', 'Dehiwala-Mount Lavinia', 'தெஹிவளை-கல்கிஸ்‍ஸ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 31, 'රත්මලාන', 'Ratmalana', 'இரத்மழா‍ணை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 33, 'මොරටුව', 'Moratuwa', 'மொரட்டு‍வை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(11, 36, 'කැස්බෑව', 'Kesbewa', '‎கெஸ்‍‍பே‍வை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 3, 'මීගමුව', 'Negombo', 'நீர்கொழும்பு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 6, 'කටාන', 'Katana', 'கடா‍ணை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 9, 'දිවුලපිටිය', 'Divulapitiya', 'திவுலப்பிட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 12, 'මීරිගම', 'Mirigama', 'மீரிகமை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 15, 'මිනුවන්ගොඩ', 'Minuwangoda', 'மிணுவாங்‎‎கொ‍டை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 18, 'වත්තල', 'Wattala', 'வத்தளை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 21, 'ජා-ඇල', 'Ja-Ela', 'ஜா-எல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 24, 'ගම්පහ', 'Gampaha', 'கம்பஹ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 27, 'අත්තනගල්ල', 'Attanagalla', 'அத்தணகல்‍லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 30, 'දොම්පෙ', 'Dompe', '‎தொம்‍பே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 33, 'මහර', 'Mahara', 'மஹற');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 36, 'කැළණිය', 'Kelaniya', 'களணி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(12, 39, 'බියගම', 'Biyagama', 'பியக‍மை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 3, 'පානදුර', 'Panadura', 'பாணத்து‍றை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 6, 'බණ්ඩාරගම', 'Bandaragama', 'பண்டாரக‍மை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 9, 'හොරණ', 'Horana', '‎ஹொற‍ணை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 10, 'ඉංගිරිය', 'Ingiriya', 'இங்கிரிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 12, 'බුලත්සිංහල', 'Bulathsinhala', 'புழத்சிங்கள');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 15, 'මදුරාවල', 'Madurawela', 'மதுரா‎வெள');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 18, 'මිල්ලනිය', 'Millaniya', 'மில்லணிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 21, 'කළුතර', 'Kalutara', 'களுத்து‍றை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 24, 'බේරුවල', 'Beruwala', '‍‍பேறுவ‍ளை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 27, 'දොඩම්ගොඩ', 'Dodangoda', '‎தொடந்தூவை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 30, 'මතුගම', 'Mathugama', 'மத்துக‍மை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 33, 'අගලවත්ත', 'Agalawatta', 'அகளவத்‍தை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 36, 'පාලින්ද නුවර', 'Palindanuwara', 'பாலிந்தநுவர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(13, 39, 'වලල්ලාවිට', 'Walallavita', 'வளள்ளாவிட்ட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 3, 'තුම්පනේ', 'Thumpane', 'தும்பணை‍');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 6, 'පුජාපිටිය', 'Poojapitiya', 'பூஜாபிட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 9, 'අකුරණ', 'Akurana', 'அக்குர‍ணை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 12, 'පාතදුම්බර', 'Pathadumbara', 'பாத்ததும்ப‍ரை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 15, 'පන්විල', 'Panvila', 'பண்வில');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 18, 'උඩදුම්බර', 'Udadumbara', 'உடதும்ப‍ரை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 21, 'මිනිපේ            *', 'Minipe', 'மினிபே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 24, 'මැදදුම්බර', 'Medadumbara', '‎மெததும்பர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 27, 'කුණ්ඩසාලෙ', 'Kundasale', 'குண்டசா‍லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 30, 'මහනුවර කඩවත් සතර හා ගඟවටකොරළේ', 'Kandy Four Gravets & Gangawata Korale', 'கண்டி கடவத்ஸதர, கங்கவட கோரலே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 33, 'හාරිස්පත්තුව', 'Harispattuwa', 'ஹரிஸ்பத்துவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 34, 'හතරලියැද්ද', 'Hatharaliyadda', 'ஹதரழி‎யெந்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 36, 'යටිනුවර', 'Yatinuwara', 'யட்டினுவர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 39, 'උඩුනුවර      *', 'Udunuwara', 'உடுனுவர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 42, 'දොළුව', 'Doluwa', '‎தொழுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 45, 'පහතහේවාහැට', 'Pathahewaheta', 'பஹத‍‍ஹேவா‎ஹெட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 48, 'දෙල්තොට', 'Delthota', '‎தெல்‎தொட்ட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 51, 'උඩපලාත', 'Udapalatha', 'உடபலாத');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 54, 'ගඟ ඉහළ කොරළේ', 'Ganga Ihala Korale', 'கங்க இஹல ‍ேகாற‍‍லே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(21, 57, 'පස්බාගේ කොරළේ', 'Pasbage Korale', 'பஸ்பா‍கே ‍கோற‍லே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 3, 'ගලේවෙල', 'Galewela', 'கலேவெல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 6, 'දඹුල්ල', 'Dambulla', 'தம்புல்ல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 9, 'නාඋල', 'Naula', 'நாஉல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 12, 'පල්ලෙපොල', 'Pallepola', 'பல்லெபொல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 15, 'යටවත්ත', 'Yatawatta', 'யடவத்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 18, 'මාතලේ', 'Matale', 'மாத்தளை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 21, 'අඹන්ගඟ කොරළේ', 'Ambanganga Korale', 'அம்பங்கககோரலே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 24, 'ලග්ගල - පල්ලෙගම', 'Laggala-Pallegama', 'லக்கல - பல்லேகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 27, 'විල්ගමුව', 'Wilgamuwa', 'வில்கமுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 30, 'රත්තොට', 'Rattota', 'ரத்தொட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(22, 33, 'උකුවෙල', 'Ukuwela', 'உகுவெல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(23, 3, 'තකාත්මලේ', 'Kothmale', '‎‎கொத்ம‍லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(23, 6, 'හඟුරන්කෙත', 'Hanguranketha', 'ஹங்குரங்‎கெத');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(23, 9, 'වලපනේ', 'Walapane', 'வலப‍‍னே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(23, 12, 'නුවර එළිය', 'Nuwara Eliya', 'நுவ‎ரெளியா');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(23, 15, 'අඹගමුව', 'Ambagamuwa', 'அம்பகமுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 3, 'බෙන්තොට', 'Benthota', '‎பென்‎தொட்டை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 6, 'බලපිටිය', 'Balapitiya', 'பலபிட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 9, 'කරන්දෙණිය', 'Karandeniya', 'கரந்‎தெனிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 12, 'ඇල්පිටිය', 'Elpitiya', 'எல்பிடி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 15, 'නියාගම', 'Niyagama', 'நியாகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 18, 'තවලම', 'Thawalama', 'தவலம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 21, 'නෙළුව', 'Neluwa', '‎நெழுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 24, 'නාගොඩ', 'Nagoda', 'நா‎கொ‍டை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 27, 'බද්දෙගම', 'Baddegama', 'பத்‍தேகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 30, 'වැලිවිටිය - දිවිතුර', 'Welivitiya-Divithura', '‎வெலிவிடிய-திவிதுர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 33, 'අම්බලන්ගොඩ', 'Ambalangoda', 'அம்பலாங்‎கொடை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 36, 'හික්කඩුව', 'Hikkaduwa', 'ஹிக்கடுவை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 39, 'ගාල්ල කඩවත් සතර', 'Galle Four Gravets', 'காலி கடவத் ஸதர(பிரதேச செயலகப் பிரிவு)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 42, 'බෝපෙ පෝද්දල', 'Bope-Poddala', '‍‎‍போ‍பே-‎பொத்தல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 45, 'අක්මීමන', 'Akmeemana', 'அக்மீமண');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 48, 'යක්කල මුල්ල', 'Yakkalamulla', 'யக்கலமுல்ல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 51, 'ඉමදූව', 'Imaduwa', 'இமதூவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(31, 54, 'හබරාදුව', 'Habaraduwa', 'ஹபராதூவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 3, 'පිටබැද්දර', 'Pitabeddara', 'பிட்ட‎பெத்தர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 6, 'කොටපොල', 'Kotapola', 'கொடபொல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 9, 'පස්ගොඩ', 'Pasgoda', 'பஸ்‎கொட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 12, 'මුලටියන', 'Mulatiyana', 'முலடியன');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 15, 'අතුරලිය', 'Athuraliya', 'அத்து‎ரெளிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 18, 'අකුරැස්ස', 'Akuressa', 'அக்கு‎ரெஸ்ஸ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 21, 'වැලිපිටිය', 'Welipitiya', 'வெலிபிடிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 24, 'මාලිම්බඩ', 'Malimbada', 'மாலிம்பட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 27, 'කඹුරුපිටිය', 'Kamburupitiya', 'கம்புறுபிடிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 30, 'හක්මන', 'Hakmana', 'ஹக்மண');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 33, 'කිරින්ද පුහුල්වැල්ල', 'Kirinda Puhulwella', 'கிரிந்த புஹுல்‎வெல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 36, 'තිහගොඩ', 'Thihagoda', 'திஹ‎கொட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 39, 'වැලිගම', 'Weligama', 'வெலிகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 42, 'මාතර', 'Matara Four Gravets', 'மாத்தறை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 45, 'දෙවිනුවර', 'Devinuwara', 'தெவிநுவர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(32, 48, 'දික්වැල්ල', 'Dickwella', 'திக்‎வெல்ல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 3, 'සූරියවැව', 'Sooriyawewa', 'சூரிய‎வெ‎வெ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 6, 'ලුණුගම්වෙහෙර', 'Lunugamvehera', 'லுணுகம்‎வெஹற');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 9, 'තිස්සමහාරාමය', 'Thissamaharama', 'திஸ்ஸமஹாராம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 12, 'හමිබන්තොට', 'Hambantota', 'ஹம்பந்‍தோட்டை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 15, 'අම්බලන්තොට', 'Ambalantota', 'அம்பலாந்‍தோட்டை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 18, 'අඟුණුකොළපැලැස්ස', 'Angunakolapelessa', 'அங்குண‎கொல‎பெ‎லெஸ்ஸ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 21, 'වීරකැටිය', 'Weeraketiya', 'வீரகெட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 24, 'කටුවන', 'Katuwana', 'கடுவண');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 27, 'උක්වෙල', 'Okewela', 'ஓ‍‍‍‍கே‎வெல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 30, 'බෙලිඅත්ත', 'Beliatta', '‎பெலியத்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(33, 33, 'තංගල්ල', 'Tangalle', 'தங்கல்லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 3, 'කයිට්ස්', 'Island North (Kayts)', 'தீவு வடக்கு (கை‍ட்ஸ்)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 6, 'වලිකාමම් බටහිර', 'Valikamam West (Chankanai)', 'வலிகாமம் ‍மேற்கு (சங்கனை)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 9, 'වලිකාමම් නිරිත', 'Valikamam South-West (Sandilipay)', 'வலிகாமம் ‎தென்‍மேற்கு (சந்திலிப்பாய்)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 12, 'වලිකාමම් උතුර', 'Valikamam North (Tellipallai)', 'வலிகாமம் வடக்கு (‎தெல்லிப்பாலை)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 15, 'වලිකාමම් දකුණ', 'Valikamam South (Uduvil)', 'வலிகாமம் தெற்கு (உடுவில்)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 18, 'වලිකාමම් නැගෙනහිර', 'Valikamam East (Kopay)', 'வலிகாமம் கிழக்கு (‍கோப்பாய்)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 21, 'වලිකාමම් නිරිත (කරවෙඩ්ඩි)', 'Vadamaradchi South-West (Karaveddy)', 'வடமராச்சி ‎தென்‍மேற்கு (கர‎வெட்டி)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 24, 'වඩමාරච්චි නැගෙනහිර', 'Vadamaradchi East (Maruthnkerny)', 'வடமராச்சி கிழக்கு ( மருத்தங்‍கேணி)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 27, 'වඩමිරච්චි උතුර', 'Vadamaradchi North (Point Pedro)', 'வடமராச்சி வடக்கு (‍பேதுருமுணை)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 30, 'තෙන්මාරච්චි', 'Thenmaradchi (Chavakachcheri)', '‎தென்மராச்சி (சாவக்கச்‍சேரி)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 33, 'නල්ලූර්', 'Nallur', 'நல்லூர்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 36, 'යාපනය', 'Jaffna', 'யாழ்ப்பாணம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 39, 'වෙලානෙයි', 'Island South (Velanai)', 'தீவு ‎தெற்கு (‍வேலணி)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(41, 42, 'ඩෙල්ෆ්', 'Delft', '‎டெல்ப்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(42, 3, 'මන්නාරම නගරය', 'Mannar Town', 'மன்னார் நகரம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(42, 6, 'මන්තායි බටහිර', 'Manthai West', 'மாந்தை ‍மேற்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(42, 9, 'මඩු', 'Madhu', 'மடு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(42, 12, 'නානාධන්', 'Nanaddan', 'நனாதன்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(42, 15, 'මුසලි', 'Musalai', 'முசலி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(43, 3, 'වවුනියා උතුර', 'Vavuniya North', 'வவுனியா வடக்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(43, 6, 'වවුනියා දකුණ', 'Vavuniya South', 'வவுனியா ‎தெற்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(43, 9, 'වවුනියා', 'Vavuniya', 'வவுனியா');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(43, 12, 'වෙන්ගලචෙඩ්ඩිකුලම්', 'Vengalacheddikulam', '‎வெங்கல‎ச்செட்டிக்குளம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(44, 3, 'තුනුක්කායි', 'Thunukkai', 'துணுக்கை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(44, 6, 'මන්තායි නැගෙනහිර', 'Manthai East', 'மாந்தை கிழக்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(44, 9, 'පුදුකුඩියිරිප්පු', 'Puthukudiyiruppu', 'புதுக்குடியிருப்பு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(44, 12, 'ඔඩ්ඩුසුදාන්', 'Oddusuddan', 'ஒட்டுச்சுட்டாண்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(44, 15, 'මැරිටයිම්පත්තු', 'Maritimepattu', 'மரிதி‍மேப்பட்டு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(45, 3, 'පච්චිලෙයිපල්ලෙයි', 'Pachchilaipalli', 'பச்சிலைப்பல்லி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(45, 6, 'කන්දවලායි', 'Kandavalai', 'கந்தவளை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(45, 9, 'කරච්චි', 'Karachchi', 'கரச்சி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(45, 12, 'පුනාකරි', 'Poonakary', 'பூணாகரி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 3, 'කෝරලේපත්තු උතුර', 'Koralai Pattu North', '‍‍‎‍‍‍‎‍கோரலைப்பத்து வடக்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 6, 'කෝරලේපත්තු බටහිර', 'Koralai Pattu West (Oddamavadi)', '‍‍‎‍கோரலைப்பத்து ‍மேற்கு ( ஓட்டமாவடி)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 9, 'කෝරලේපත්තු', 'Koralai Pattu (Valachchenai)', '‍‍‎‍கோரலைப்பத்து (வாழச்சேனை)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 12, 'එරාවුර්පත්තු', 'Eravur Pattu', 'ஏறாவூர் பட்டு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 15, 'එරාවුර් නගරය', 'Eravur Town', 'ஏறாவூர் நகரம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 18, 'මන්මුනායි උතුර', 'Manmunai North', 'மண்முணை வடக்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 21, 'මන්මුනායි බටහිර', 'Manmunai West', 'மண்முணை ‍மேற்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 24, 'කාත්තන්කුඩි', 'Kattankudy', 'காத்தாங்குடி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 27, 'මන්මුනායිපත්තු', 'Manmunai Pattu (Araipattai)', 'மண்முணை பட்டு (அரைப்பட்டை)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 30, 'මන්මුනායි නිරිත', 'Manmunai South-West', 'மண்முணை ‎தென்‍மேற்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 33, 'පෝරතිවිපත්තු', 'Porativu Pattu', '‍போரதீவு பட்டு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 36, 'මන්මුනෙයි දකුණ හා එරුවිල්පත්තු', 'Manmunai South & Eruvil Pattu', 'மண்முணை ‎தெற்கு,எருவில்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(51, 39, 'කෝරළේපත්තු දකුණ', 'Koralai Pattu South (Kiran)', '‍‍‍‍‎‍கோரலைப்பத்து ‎தெற்கு (கிராண்)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 3, 'දෙහිඅත්තකන්ඩිය', 'Dehiattakandiya', '‎தெஹிஅத்தக்கண்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 6, 'පදියතලාව', 'Padiyathalawa', 'பதியதலாவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 9, 'මහඔය', 'Mahaoya', 'மஹாஓயா');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 12, 'උහන', 'Uhana', 'உஹண');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 15, 'අම්පාර', 'Ampara', 'அம்பாறை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 16, 'නාවිතන්විලි', 'Navithanveli', 'நவிதண்‎‍வேலி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 18, 'සමන්තුරෙයි', 'Samanthurai', 'சம்மாந்துரை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 24, 'කල්මුනෙයි', 'Kalmunai', 'கல்முனை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 25, 'සෙයින්තමරතු', 'Sainthamarathu', 'சாய்ந்தமருது');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 27, 'කරතිවු', 'Karativu', 'காரைத்தீவு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 30, 'නිනිතවූර්', 'Ninthavur', 'நிந்தவூர்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 33, 'අඩ්ඩාලච්චේනායි', 'Addalachchenai', 'அட்டால‍ச்சேனை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 34, 'එරගම', 'Eragama', 'எரகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 36, 'අක්කරෙයිපත්තු', 'Akkaraipattu', 'அக்கரைப்பத்து');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 39, 'අලයඩිවෙම්බු', 'Alayadiwembu', 'அலையடி‍வேம்பு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 42, 'දමන', 'Damana', 'தமண');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 45, 'තිරුක්කෝවිල්', 'Thirukkovil', 'திருக்‍கோவில்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 48, 'පොතුවිල්', 'Pothuvil', '‎பொத்துவில்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(52, 51, 'ලාහුගල', 'Lahugala', 'லாஹுகலை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 3, 'පදවි ශ්‍රි පුර', 'Padavi Sri Pura', 'பதவி ஸ்ரீ புர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 6, 'කුච්චවේලි', 'Kuchchaveli', 'குச்ச‍வேலி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 9, 'ගෝමරන්කඩවල', 'Gomarankadawala', '‍கோமரங்கடவல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 12, 'මොරවැව', 'Morawewa', '‎மொற‎வெவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 15, 'ත්‍රිකුණාමලය නගරය හා කඩවත්', 'Trincomalee Town and Gravets', 'திரு‍கோணமலை நகரம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 18, 'තඔලගමුව', 'Thambalagamuwa', 'தம்பலகமுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 21, 'කන්තලේ', 'Kantalai', 'கந்தளாய்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 24, 'කින්නියා', 'Kinniya', 'கின்னியா');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 27, 'මුත්තූර්', 'Muttur', 'மூதூர்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 30, 'සේරුවිල', 'Seruvila', '‍சேருவில்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(53, 33, 'වෙරුගල්/ඉච්චලම්පත්තු', 'Verugal (Echchilampattai)', '‎வெருகல் (இச்சிழம்பத்து)');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 3, 'ගිරිබාව', 'Giribawa', 'கிரிபாவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 6, 'ගල්ගමුව', 'Galgamuwa', 'கல்கமுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 9, 'ඇහැටුවැව', 'Ehetuwewa', 'எ‎‎ஹெடு‎வெவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 12, 'අඹන්පොළ', 'Ambanpola', 'அம்பண்‎பொல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 15, 'කොටවෙහෙර', 'Kotavehera', 'கொடவெஹெர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 18, 'රස්නායකපුර', 'Rasnayakapura', 'ரஸ்நாயக்கபுர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 21, 'නිකවෙරටිය', 'Nikaweratiya', 'நிக்க‎வெரட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 24, 'මහව', 'Mahawa', 'மஹவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 27, 'පොල්පිතිගම', 'Polpithigama', 'பொல்பிதிகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 30, 'ඉබ්බාගමුව', 'Ibbagamuwa', 'இப்பாகமுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 33, 'ගනේවත්ත', 'Ganewatta', 'க‍னேவத்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 36, 'වාරියපොල', 'Wariyapola', 'வாரிய‎பொல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 39, 'කොබෙයිගනේ', 'Kobeigane', 'கொபெய்கனே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 42, 'බිංගිරිය', 'Bingiriya', 'பிங்கிரிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 45, 'පඩුවස්නුවර', 'Panduwasnuwara', 'பண்டுவஸ்நுவர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 48, 'කටුපොත', 'Katupotha', 'கடு‎பொத');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 49, 'බමුණාකොටුව', 'Bamunakotuwa', 'பமுண‎கொட்டுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 51, 'මාස්පොත', 'Maspotha', 'மஸ்‎பொத');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 54, 'කුරුණෑගල', 'Kurunegala', 'குருணாக‍லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 57, 'මල්ලවපිටිය', 'Mallawapitiya', 'மல்லவபிட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 60, 'මාවතගම', 'Mawathagama', 'மாவத்தகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 63, 'රිදීගම', 'Rideegama', 'ரிதீகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 66, 'වීරඹුගෙදර', 'Weerambugedara', 'வீரம்பு‎கெதர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 69, 'කුළියාපිටිය නැගෙනහිර', 'Kuliyapitiya East', 'குளியாபிட்டிய கிழக்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 72, 'කුළියාපිටිය බටහිර', 'Kuliyapitiya West', 'குளியாபிட்டிய ‍மேற்கு');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 75, 'උඩුබද්දාව', 'Udubaddawa', 'உடுபத்தாவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 78, 'පන්නල', 'Pannala', 'பன்னல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 81, 'නාරම්මල', 'Narammala', 'நாரம்மல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 84, 'අලව්ව', 'Alawwa', 'அலவ்வ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(61, 87, 'පොල්ගහවෙල', 'Polgahawela', 'பொல்கஹவெல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 3, 'කල්පිටිය', 'Kalpitiya', 'கல்பிடிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 6, 'වනාතවිල්ලුව', 'Vanathavilluwa', 'வனாத்தவில்லுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 9, 'කරුවලගස්වැව', 'Karuwalagaswewa', 'கருவலகஸ்‎வெவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 12, 'නවගත්තේගම', 'Nawagattegama', 'நவகத்‍தேகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 15, 'පුත්තලම', 'Puttalam', 'புத்தளம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 18, 'මුන්දලම', 'Mundalama', 'முந்தலம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 21, 'මහකුඹුක්කඩවල', 'Mahakumbukkadawala', 'மஹகும்புக்கடவல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 24, 'ආනමඩුව', 'Anamaduwa', 'ஆணமடுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 27, 'පල්ලම', 'Pallama', 'பல்லம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 30, 'ආරච්චිකට්ටුව', 'Arachchikattuwa', 'ஆரச்சிகட்டுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 33, 'හලාවත', 'Chilaw', 'சிலாபம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 36, 'මාදම්පෙ', 'Madampe', 'மாதம்‍பே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 39, 'මහවැව', 'Mahawewa', 'மஹா‎வெவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 42, 'නාත්තන්ඩිය', 'Nattandiya', 'நாத்தண்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 45, 'වෙන්නප්පුව', 'Wennappuwa', 'வெண்ணப்புவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(62, 48, 'දංකොටුව', 'Dankotuwa', 'தங்‎‎கொட்டுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 3, 'පදවිය', 'Padaviya', 'பதவிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 6, 'තැබිතිගොල්ලෑව', 'Kebithigollewa', '‎‎கெபித்தி‎கொல்‍லேவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 9, 'මැදවච්චිය', 'Medawachchiya', '‎மெதவச்சிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 12, 'මහවිලච්චිය', 'Mahavilachchiya', 'மஹவிலச்சிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 15, 'නුවරගම් පළාත මධ්‍යම', 'Nuwaragam Palatha Central', 'மத்திய நுவரகம் பலாத்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 18, 'රඹෑව', 'Rambewa', 'ரம்பேவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 21, 'කහටගස්දිගිලිය', 'Kahatagasdigiliya', 'கஹட்டகஸ்திகிலிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 24, 'හොරොව්පතාන', 'Horowpothana', '‎ஹொ‎றொவ்பதாண');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 27, 'ගලෙන්බිදුනුවැව', 'Galenbindunuwewa', 'க‎லெண்பிந்துணு‎வெவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 30, 'මිහින්තලේ', 'Mihinthale', 'மிஹிந்த‍லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 33, 'නුවරගම් පළාත නැගෙනහිර', 'Nuwaragam Palatha East', 'கிழக்கு நுவரகம் பலாத்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 36, 'නාච්චදුව', 'Nachchadoowa', 'நாச்சதூ‍வை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 39, 'නොච්චියාගම', 'Nochchiyagama', '‎நொச்சியாகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 42, 'රාජාංගනය', 'Rajanganaya', 'இராஜ்ஜாங்கணய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 45, 'තඹුත්තෙගම', 'Thambuttegama', 'தம்புத்‍தேகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 48, 'තලාව', 'Thalawa', 'தலாவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 51, 'තිරිප්පනේ', 'Thirappane', 'திரப்ப‍ணே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 54, 'කැකිරාව', 'Kekirawa', '‎கெகிராவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 57, 'පලුගස්වැව', 'Palugaswewa', 'பலுகஸ்‎வெவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 60, 'ඉපලෝගම', 'Ipalogama', 'இப‍லோகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 63, 'ගල්නෑව', 'Galnewa', 'கல்‍ணேவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 66, 'පලාගල', 'Palagala', 'பலாகல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(71, 69, 'වැලිඔය', 'Welioya', '‎வெலிஓய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(72, 3, 'හිඟුරක්ගොඩ', 'Hingurakgoda', 'ஹிங்குரக்‎கொடை‍');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(72, 6, 'මැදිරිගිරිය', 'Medirigiriya', '‎மெதிரிகிரிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(72, 9, 'ලංකාපුර', 'Lankapura', 'லங்காபுர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(72, 10, 'වැලිකන්ද', 'Welikanda', '‎வெலிகந்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(72, 12, 'දිඹුලාගල', 'Dimbulagala', 'திம்புலாகல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(72, 15, 'තමන්කඩුව', 'Thamankaduwa', 'தமண்கடுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(72, 18, 'ඇලහැර', 'Elahera', 'எல‎ஹெற');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 3, 'මහියංගනය', 'Mahiyanganaya', 'மஹியங்க‍ணை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 6, 'රිදීමාලියද්ද', 'Rideemaliyadda', 'ரிதீமாலியத்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 9, 'මීගහකිවුල', 'Meegahakivula', 'மீகஹகிவுல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 12, 'කන්දකැටිය', 'Kandaketiya', 'கந்த‎கெட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 15, 'සොරණතොට', 'Soranathota', '‎சொறண‎தொட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 18, 'පස්සර', 'Passara', 'பச‍ரை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 19, 'ලුණුගල', 'Lunugala', 'லுணுக‍லை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 21, 'බදුල්ල', 'Badulla', 'பதுளை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 24, 'හාලිඇල', 'Hali-Ela', 'ஹாலி-எல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 27, 'ඌව-පරණගම', 'Uva-Paranagama', 'ஊவா-பரணகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 30, 'වැලිමඩ', 'Welimada', '‎வெலிம‍டை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 33, 'බණ්ඩාරවෙල', 'Bandarawela', 'பண்டாரவளை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 36, 'ඇල්ල', 'Ella', 'எல்ல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 39, 'හපුතලේ', 'Haputale', 'ஹபுத‍லே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(81, 42, 'හල්දුම්මුල්ල', 'Haldummulla', 'ஹல்துமுள்ள');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 3, 'බිබිලේ', 'Bibile', 'பிபிலை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 6, 'මඩුල්ල', 'Madulla', 'மதுள்‍ள');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 9, 'මැදගම', 'Medagama', '‎மெதகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 12, 'සියඹලාන්ඩුව', 'Siyambalanduwa', 'சியம்பலாண்டுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 15, 'මොනරාගල', 'Moneragala', '‎மொணராகலை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 18, 'බඩැල්කුඹුර', 'Badalkumbura', 'படல்கும்புர');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 21, 'වැල්ලවාය', 'Wellawaya', '‎வெல்லவாய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 24, 'බුත්තල', 'Buttala', 'புத்தலை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 27, 'කතරගම', 'Katharagama', 'கதிர்காமம்');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 30, 'තනමල්විල', 'Thanamalvila', 'தணமல்வில');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(82, 33, 'සෙවනගල', 'Sevanagala', '‎செவணகல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 3, 'ඇහැලියගොඩ', 'Eheliyagoda', 'எஹலிய‎‎கெடை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 6, 'කුරුවිට', 'Kuruvita', 'குருவிட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 9, 'කිරිඇල්ල', 'Kiriella', 'கிரிஎல்ல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 12, 'රත්නපුර', 'Ratnapura', 'இரத்திணபுரி');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 15, 'ඉඹුල්පෙ', 'Imbulpe', 'இம்புல்‍பே');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 18, 'බලන්ගොඩ', 'Balangoda', 'பலாங்‎கொடை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 21, 'ඕපනායක', 'Opanayaka', 'ஓபணாயக்க');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 24, 'පැල්මඩුල්ල', 'Pelmadulla', '‎பெல்மடுல்ல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 27, 'ඇලපාත', 'Elapatha', 'எலபாத');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 30, 'අයගම', 'Ayagama', 'அயகம');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 33, 'කලවාන', 'Kalawana', 'கலவான');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 36, 'නිවිතිගල', 'Nivithigala', 'நிவித்திகல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 39, 'කහවත්ත', 'Kahawatta', 'கஹவத்த');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 42, 'ගොඩකවෙල', 'Godakawela', '‎கொடக‎வெல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 45, 'වැලිගෙපොල', 'Weligepola', '‎வெலி‍‍கே‎பொல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 48, 'ඇඹිලිපිටිය', 'Embilipitiya', 'எம்பிலிபிட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(91, 51, 'කොලොන්න', 'Kolonna', '‎கொ‎லொண்ண');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 3, 'රඹුක්කන', 'Rambukkana', 'ரம்புக்கணை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 6, 'මාවනැල්ල', 'Mawanella', 'மாவ‎ணெல்ல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 9, 'අරනායක', 'Aranayaka', 'அரநாயக்க');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 12, 'කෑගල්ල', 'Kegalle', '‍கேகாலை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 15, 'ගලිගමුව', 'Galigamuwa', 'கலிகமுவ');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 18, 'වරකාපොළ', 'Warakapola', 'வரகாப்‎பொல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 21, 'රුවන්වැල්ල', 'Ruwanwella', 'ருவண்‎வெல்ல');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 24, 'බුලත්කොහුපිටිය', 'Bulathkohupitiya', 'புலத்‎கொஹுபிட்டிய');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 27, 'යටියන්තොට', 'Yatiyanthota', 'யட்டியந்‎தொட்டை');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 30, 'දෙහිඹ්විට', 'Dehiovita', '‎தெஹி‍யோவிட்ட');
INSERT INTO COMMON.DS_DIVISIONS(districtId, divisionId, siDivisionName, enDivisionName, taDivisionName) VALUES(92, 33, 'දැරණියගල', 'Deraniyagala', '‎தெரணியகல');
