CREATE DATABASE `epopulation` DEFAULT CHARACTER SET utf8;

USE `epopulation`;

DROP TABLE IF EXISTS `birth_register`;

CREATE TABLE `birth_register` (
  `serialNumber` VARCHAR(20) NOT NULL,
  `childDOB` DATETIME,
  `childBirthDistrict` VARCHAR(50),
  `childBirthDivision` VARCHAR(50),
  `childBirthPlace` VARCHAR(50),
  `childFullNameOfficialLang` VARCHAR(100) ,
  `childFullNameEnglish` VARCHAR(100),
  `childGender` CHAR ,
  `childBirthWeight` FLOAT,
  `noOfLiveChildren` INTEGER,
  `noOfMultipleBirths` INTEGER ,
  `hospitalOrGNCode` VARCHAR(20),
  `fathersNIC` VARCHAR(10),
  `fatherForeignerPassportNo` VARCHAR(10) ,
  `fatherForeignerCountry` VARCHAR(50) ,
  `fatherFullName` VARCHAR(100),
  `fatherDOB` DATETIME,
  `fatherBirthPlace` VARCHAR(50),
  `fatherRace` VARCHAR(20),
  `motherNIC` VARCHAR(10),
  `motherPassportNo` VARCHAR(10) ,
  `motherContry` VARCHAR(50) ,
  `motherAdmissionNoAndDate` VARCHAR(60),
  `motherFullName` VARCHAR(50),
  `motherDOB` DATETIME,
  `motherBirthPlace` VARCHAR(50),
  `motherRace` VARCHAR(20),
  `motherAgeAtBirth` INTEGER,
  `motherAddress` VARCHAR(100),
  `motherPhoneNo` VARCHAR(10),
  `motherEmail` VARCHAR(50),
  `placeOfMarriage` VARCHAR(50) ,
  `dateOfMarriage` DATETIME ,
  `grandFatherFullName` VARCHAR(100) ,
  `grandFatherBirthYear` VARCHAR(4) ,
  `grandFatherBirthPlace` VARCHAR(50) ,
  `greatGrandFatherFullName` VARCHAR(100) ,
  `greatGrandFatherBirthYear` VARCHAR(4) ,
  `greatGrandFatherBirthPlace` VARCHAR(50) ,
  `informant` VARCHAR(10),
  `informantName` VARCHAR(100),
  `informantNIC` VARCHAR(10),
  `informantPostalAddress` VARCHAR(100),
  `informantPhoneNo` VARCHAR(10),
  `informantEmail` VARCHAR(50),
  `authority` VARCHAR(50),      
  PRIMARY KEY (`serialNumber`)
)ENGINE=MyISAM AUTO_INCREMENT=90000 DEFAULT CHARSET=utf8;